### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Tools/Compressonator#1]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [gtAutoPtr](https://github.com/GPUOpen-Tools/Compressonator/blob/168db0b9cd4c0e9e6c434f7eccf2cb647aabebef/Compressonator/Applications/CompressonatorGUI/CXL/Include/AMDTBaseTools/Include/gtAutoPtr.h#L62 "Destructor for gtAutoPtr")
* [ProjectView](https://github.com/raboof/nethogs/blob/e7a74b00fb0ae596cc214bdd9de158c7bce0d3da/src/connection.h#L34 "Destructor for ProjectView")
* [QtButtonPropertyBrowserPrivate::propertyRemoved](https://github.com/GPUOpen-Tools/Compressonator/blob/168db0b9cd4c0e9e6c434f7eccf2cb647aabebef/Compressonator/Applications/CompressonatorGUI/QPropertyPages/qtbuttonpropertybrowser.cpp#L341 "QtButtonPropertyBrowserPrivate::propertyRemoved function")

**Comment by NPCompress** [comment]
Thank you for your suggestion, we will continue to optimize the code as pointed out.

**Comment by elfring** [comment]
Which commits will improve the affected source files?
