### ISSUE TITLE
RXGB Support

### ISSUE THREAD

**Issue by nbohr1more** [GPUOpen-Tools/Compressonator#10]
Please add RXGB support back to this project.

The GPL release of Doom 3 will mean that many open source study projects will need that format for normal map compression.

Thanks!

**Comment by NPCompress** [comment]
RXGB is been mapped to DXT5_xGBR with the red component swizzled into the Alpha channel
Let us know if there are issues with this mapping.

Thanks.

**Comment by nbohr1more** [comment]
Thank you!
