### ISSUE TITLE
No clear option to specify gamma when generating mipmaps

### ISSUE THREAD

**Issue by dmaluev** [GPUOpen-Tools/compressonator#102]
Hello! I cannot find an option to tell Compressonator whether my source image has color data or some arbitrary data. It seems like mipmaps are generated just by summing original values in non-linear space, which is clearly wrong for color data. For example, if my image has black (0) and white (255) bars, mipmap will have color value 128, but it should be 188 for color data.

**Comment by NPCompress** [comment]
@dmaluev Thanks for reporting the issue. The MipMap code generation is been reworked for improvements and bug fixes.

**Comment by NPCompress** [comment]
@dmaluev code is been updated for v4.1 release to allow additional filter options to be used,
