### ISSUE TITLE
BC1 and BC3 RGB result is different

### ISSUE THREAD

**Issue by SimpsonGSD** [GPUOpen-Tools/compressonator#104]
Hi, as far as I'm aware BC1 and BC3 should produce the same result for RGB data for the same input texture. However, with high frequency data in the blue channel BC1 produces RG data with blue data in but in BC3 the RG data is almost unaffected by the blue channel. Why is this? Which one is correct? For my needs BC3 produces a much better RGB result, I just don't need any alpha as it's black.

**Comment by NPCompress** [comment]
@SimpsonGSD  Are you using the application GUI, CLI,  or the Libraries CMP_Core, Compressonator?

**Comment by SimpsonGSD** [comment]
I was testing with the GUI.

**Comment by NPCompress** [comment]
@SimpsonGSD  In the GUI Set Application options dialog are you using "Encode with" CPU or HPC?

![image](https://user-images.githubusercontent.com/18406717/81310271-e2cc1e00-9051-11ea-99a9-de1fdea17eac.png)

**Comment by SimpsonGSD** [comment]
@NPCompress CPU

**Comment by SimpsonGSD** [comment]
I've just tested this with 4.0 GUI and BC1 and BC3 now produce the same result. The result is now worse than the BC3 output from 3.2 but at least they are consistent. I've attached my unit test texture. 
![BC1_UnitTest](https://user-images.githubusercontent.com/11320611/82054263-8baff400-96b6-11ea-85b9-13ab945f7fa3.png)

**Comment by NPCompress** [comment]
@SimpsonGSD  What is the quality setting?
Have you tried HPC with q=1.0?

**Comment by SimpsonGSD** [comment]
@NPCompress Yeah I have HPC encode enabled and quality 1.0.

**Comment by NPCompress** [comment]
@SimpsonGSD  HPC PSNR is expected to be about -0.2dB from CPU, The CPU decoder codec had a fix that may also make a diff in PSNR calc.

**Comment by NPCompress** [comment]
@SimpsonGSD I will look at the sample to see if quality can be improved for the next update

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
