### ISSUE TITLE
Corruption in BCn texture with unaligned size

### ISSUE THREAD

**Issue by baldurk** [GPUOpen-Tools/compressonator#105]
[This image ](https://user-images.githubusercontent.com/661798/81294565-fe8def00-9066-11ea-9564-484992482977.png) is a PNG that's 2048x1572. So that gives a mip chain of:

* 0: 2048x1572
* 1: 1024x786
* 2: 512x393
* 3: 256x196
* 4: 128x98
* 5: 64x49
* 6: 32x24
* 7: 16x12
* 8: 8x6
* 9: 4x3
* 10: 2x1

Where the important thing is that many of these don't divide evenly into 4x4 blocks. This should be fine, since just like the mip tail the dimensions are aligned up to the nearest block size and the blocks are only partially used along the edge. However when running through compressonator like this:

`CompressonatorCLI.exe -fd BC1 -miplevels 11 test.png test.dds`

I get
[this dds (zipped for github)](https://github.com/GPUOpen-Tools/compressonator/files/4592928/test.zip) where the extra partially-used row on each uneven mip displays corruption. This is more obvious on the low mips but it seems to be present on all of them:

![image](https://user-images.githubusercontent.com/661798/81294969-91c72480-9067-11ea-9027-e1596461966c.png)

The same thing can happen if the width is unaligned.

(Note if you use renderdoc to view the dds you'll need to grab latest code, as I just fixed some issues to do with these unaligned mip sizes myself!)

**Comment by NPCompress** [comment]
@baldurk  Thanks for reporting the issue, Will set up the latest RenderDoc build and work on a fix for the issue been generated by the command-line tool.

**Comment by NPCompress** [comment]
@baldurk The issue has been reproduced and is evident only when encoding with the "CPU" which uses CMP_Compressonator SDK, HPC which uses CMP_Framework seems to be ok with the sample provided. A fix is been worked on. The issue is not relevant for encoding with GPU as the images have to be divisible by 4 for the encoding to proceed.

**Comment by NPCompress** [comment]
Master src branch has the fix
