### ISSUE TITLE
Is there a test DDS data set to verify that nothing has broken? 

### ISSUE THREAD

**Issue by Zelex** [GPUOpen-Tools/compressonator#108]

**Comment by NPCompress** [comment]
@zelex there is only a small sample set of dds files. It's not comprehensive to over all compression types and image formats. Testing also includes a mixture of other file formats like its ktx png tiff etc. Catch2 is used to test at block level along with samples generated by the cli apps analysis options. Can use more dds files if open source samples are available

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
