### ISSUE TITLE
Cubemap support

### ISSUE THREAD

**Issue by Zelex** [GPUOpen-Tools/compressonator#109]
I tried opening up a cubemap and it only showed 1 face? How do I view the other faces? 

Also how do I encode a cubemap?

**Comment by NPCompress** [comment]
@Zelex  Attached is a sample cubemap   dds file.  If the sample you have is not doing what is explained below, please attach it to this issue for investigation.

Place the unzipped file into a directory say test, Using the  GUI app you then either add the file to GUI Project Explorer using the "Double click here to add files ..." or just drag and drop the file from a "Windows Explorer" test folder view to the GUI project explorer as shown:

![image](https://user-images.githubusercontent.com/18406717/82692562-efde3500-9c2d-11ea-94ea-3a43f0eb940f.png)

if you click on the image icon in the "Project Explorer" it will show the image content in an "Image view panel" where you can view each cube face using the "Frame" dropdown.

![image](https://user-images.githubusercontent.com/18406717/82692658-1e5c1000-9c2e-11ea-9774-56ed8e62702e.png)

You can also generate mip levels for the sample using the tool bar.

![image](https://user-images.githubusercontent.com/18406717/82692761-46e40a00-9c2e-11ea-8a43-039a565bf540.png)

When MIP levels are generated for each cube face, you can also view the resulting image as before, but this time the image view will also add miplevel views. 

![image](https://user-images.githubusercontent.com/18406717/82692883-801c7a00-9c2e-11ea-8015-78509ef34d6b.png)

To compress the sample. Double click on the "Add destination setting .." and process the image as instructed in the document: https://compressonator.readthedocs.io/en/latest/gui_tool/getting_started/GettingStarted.html#getting-started-using-sample-projects  step 5 onwards.

The decompressed image views will display the faces and miplevels of the image as before for comparison with the original

[Sky128.zip](https://github.com/GPUOpen-Tools/compressonator/files/4669395/Sky128.zip)

**Comment by Zelex** [comment]
Thank you! :) How do I construct a cubemap from separate png files for example?

**Comment by Zelex** [comment]
oh yeah, I updated to latest version and now I can view the faces. Guess that is a new feature.

**Comment by Zelex** [comment]
"CompressonatorCLI.exe   X:/radgit/media/dds/Sky128.dds   X:/radgit/media/dds/Sky128_DDS_ARGB_8888_1.DDS   -fd ARGB_8888  -miplevels 7  -NumThreads 64 
Error: Transcoding Cube Maps is not supported."

nooooo lol :) very new feature it seems

**Comment by Zelex** [comment]
Also, with that example Sky128 file you sent, your swapping R,B so the colors are wrong in the GUI (pretty sure)

**Comment by NPCompress** [comment]
@Zelex  Yes cube map support is fairly new and still needs more work to support all image source formats.
