### ISSUE TITLE
Windows 64 bit version?

### ISSUE THREAD

**Issue by max20091** [GPUOpen-Tools/Compressonator#11]
Is there any chance to release prebuilt 64bit version to download?

**Comment by xooiamd** [comment]
The compressonator sdk did support 64bit build. but for the gui and commandline app now is running on 32bit configuration which run fine in 64 bit system as well. We will add 64 bit build to the app later, please keep an eye on the commit. Thanks.

**Comment by NPCompress** [comment]
The SDK library , CLI and GUI application sources are 64 bit compliant, however the 3rd party lib used to link them are still 32 bit. We are in process of updating them and will post new binaries soon.

**Comment by aboood40091** [comment]
Thanks. :)

BTW what command do I use if I want no mipmaps?

**Comment by NPCompress** [comment]
You can set the command line with -nomipmap
To see all of the commands simply run CompressonatorCLI with no parameters

**Comment by aboood40091** [comment]
Thanks. :)

Instant Close. :(

**Comment by xooiamd** [comment]
@aboood40091 , can you elaborate more on "instant close" issue? what commands did you run? thanks,

**Comment by aboood40091** [comment]
When I run CompressonatorCLI with no parameters, it opens and closes at the same time.

**Comment by xooiamd** [comment]
please run by typing the command "CompressonatorCLI" in the command window, instead of double click on the CLI app.

**Comment by aboood40091** [comment]
That's exactly what I did.

**Comment by NPCompress** [comment]
64 Bit applications available in V2.4 release
