### ISSUE TITLE
Excessive alpha blockiness on mip map > 0

### ISSUE THREAD

**Issue by andre-ferreira** [GPUOpen-Tools/compressonator#120]
Hello!

When building mipmaps and compressing to BC7 from the highest level mip, anything below the first mipmap gets great RGB quality but the alpha channel is too blocky:

Alpha Mipmap0 with BC7:
![image](https://user-images.githubusercontent.com/5160177/86143683-a74b4e80-baec-11ea-97d0-bc53d1d52fa3.png)

Alpha Mipmap1 with BC7:
![image](https://user-images.githubusercontent.com/5160177/86143753-bd590f00-baec-11ea-8f5b-bbaf7b037ee8.png)

For comparison here is the overlay with RGBA for mipmap1:
![image](https://user-images.githubusercontent.com/5160177/86143889-e6799f80-baec-11ea-9e97-71ff50f21461.png)

As it can be seen, the alpha blocks are much bigger than the RGB blocks. Mipmap 0 gets great RGBA values.

Is there any setting i can tune to get sharper alpha?
If code is needed i can also provide it as well.

Thanks!
André

**Comment by NPCompress** [comment]
@andre-ferreira   Please provide code for addressing this issue. 

"Is there any setting i can tune to get sharper alpha?" What quality setting did you try was it at q=1.0 for BC7

if this fails to resolve the issue, please file an feature improvement issue to add mipmap sharpness control settings!

**Comment by andre-ferreira** [comment]
This is the full code:
```
                //---------------
		// Input MipMap
		//---------------
		CMP_MipSet MipSetIn;
		memset(&MipSetIn, 0, sizeof(CMP_MipSet));
		
		MipSetIn.dwWidth = image.m_imageWidth;
		MipSetIn.dwHeight = image.m_imageHeight;
		MipSetIn.m_nWidth = image.m_imageWidth;
		MipSetIn.m_nHeight = image.m_imageHeight;
		MipSetIn.m_nDepth = 1;
		MipSetIn.m_ChannelFormat = chFormat;
		MipSetIn.m_format = srcFormat;

		if (isNormalMap)
			MipSetIn.m_TextureDataType = TextureDataType::TDT_NORMAL_MAP;

		if (image.m_nChannels == 4)
			MipSetIn.m_TextureDataType = TextureDataType::TDT_ARGB;
		else if (image.m_nChannels == 3)
			MipSetIn.m_TextureDataType = TextureDataType::TDT_XRGB;

		uint32_t requestLevel = 10; // Request 10 miplevels for the source image

		//========================
		// Process ConvertTexture
		//========================
	
		//----------------------------------------------------------------------
		// generate mipmap level for the source image, if not already generated
		//----------------------------------------------------------------------

		MipSetIn.m_nMipLevels = 1;
		MipSetIn.m_nMaxMipLevels = requestLevel;
		CMP_MipLevelTable* mipLevelTable = new CMP_MipLevelTable[requestLevel+1];

		//Allocate mips for each set
		for (uint32_t i = 0; i < requestLevel+1; i++)
			mipLevelTable[i] = new CMP_MipLevel();

		MipSetIn.m_pMipLevelTable = mipLevelTable;

		/////////////////////////////////////////////////
		// Set the first mip map
		std::vector<unsigned char> firstMipMapData = image.GetImageData(0);

		// If we have only 3 components then we need to pad the alpha
		if (image.m_nChannels == 3)
		{
			std::vector<unsigned char> paddedMipMapData;
		
			for (size_t i = 0; i < firstMipMapData.size(); i += 3)
			{
				paddedMipMapData.emplace_back(firstMipMapData[i]);
				paddedMipMapData.emplace_back(firstMipMapData[i + 1]);
				paddedMipMapData.emplace_back(firstMipMapData[i + 2]);
				paddedMipMapData.emplace_back(255);
			}

			firstMipMapData = paddedMipMapData;
		}

		unsigned char* firstMip = new unsigned char[firstMipMapData.size()];
		memcpy(firstMip, firstMipMapData.data(), firstMipMapData.size());

		mipLevelTable[0]->m_dwLinearSize = firstMipMapData.size();
		mipLevelTable[0]->m_pbData = firstMip;
		mipLevelTable[0]->m_nHeight = image.m_imageHeight;
		mipLevelTable[0]->m_nWidth = image.m_imageWidth;

		//------------------------------------------------------------------------
		// Checks what the minimum image size will be for the requested mip levels
		// if the request is too large, a adjusted minimum size will be returns
		//------------------------------------------------------------------------
		CMP_INT nMinSize = CMP_CalcMinMipSize(MipSetIn.m_nHeight, MipSetIn.m_nWidth, requestLevel);


		//--------------------------------------------------------------
		// now that the minimum size is known, generate the miplevels
		// users can set any requested minumum size to use. The correct
		// miplevels will be set acordingly.
		//--------------------------------------------------------------
		CMP_GenerateMIPLevels(&MipSetIn, nMinSize);
			

		//------------------------------------------------
		// Initializing the Host Framework
		// if it fails revert to CPU version of the codec
		//------------------------------------------------
		KernelOptions   kernel_options;
		memset(&kernel_options, 0, sizeof(KernelOptions));
		kernel_options.format = dstFormat;
		//kernel_options.encodeWith = CMP_Compute_type::CMP_GPU_DXC; // DX does not produce good results yet
		kernel_options.encodeWith = CMP_Compute_type::CMP_HPC;
		kernel_options.fquality = imageQuality;
		kernel_options.threads = 0;
		kernel_options.srcfile = NULL;
			
		//--------------------------------------------------------------
		// Setup a results buffer for the processed file,
		// the content will be set after the source texture is processed
		// in the call to CMP_ConvertMipTexture()
		//--------------------------------------------------------------
		CMP_MipSet MipSetCmp;
		memset(&MipSetCmp, 0, sizeof(CMP_MipSet));

		//--------------------------------------------------------------
		// We need to call this with a dummy name register the plugins
		//--------------------------------------------------------------
		CMP_LoadTexture("", &MipSetIn);

		//------------------------------------------------
		// Compress the texture using Compressonator Lib
		//------------------------------------------------

		CMP_ERROR cmp_status;
		cmp_status = CMP_ProcessTexture(&MipSetIn, &MipSetCmp, kernel_options, CompressionCallback);
		if (cmp_status != CMP_OK) 
		{
			CMP_FreeMipSet(&MipSetIn);
			HL_WARN("Compression returned an error: ");
			HL_WARN(Get().ConvertCompressonatorErrorCodes(cmp_status).c_str());
		}
		else
		{
			for (size_t i = 0; i < requestLevel; i++)
				image.SetImageData(std::vector<unsigned char>(MipSetCmp.m_pMipLevelTable[i]->m_pbData, MipSetCmp.m_pMipLevelTable[i]->m_pbData + MipSetCmp.m_pMipLevelTable[i]->m_dwLinearSize), i);

			CMP_FreeMipSet(&MipSetIn);
		}

		// Copy some stats
		image.m_imageMetadata.m_compressionQuality = imageQuality;
		image.m_imageMetadata.m_imageCompressionType = compression;
	}
```

Note that the alpha and rgb compression works perfectly for mipmap 0, its the other ones below that suffer in the alpha.
Yeah, i used quality = 1.0, i can try with one different than that one, to see what results i get.

**Comment by andre-ferreira** [comment]
Changing the quality to lower (0.9 for example) does not seem to change anything

**Comment by NPCompress** [comment]
@andre-ferreira  After review of this issue, in order to improve the quality, a few new options other then quality setting should be added to KernelOptions structure to have more control over how BC7 codec is processing the blocks using CMP_ProcessTexture. This will include a BC7 mode mask that will allow users to specify using modes 5 to 7 for alpha channel blocks exclusively or only use a single mode 5 where alpha is 8 bits, additional options parameter  may also be added to CMP_GenerateMIPLevels to improve the "sharpness" of the generated mip map levels  prior to encoding.

**Comment by andre-ferreira** [comment]
> @andre-ferreira After review of this issue, in order to improve the quality, a few new options other then quality setting should be added to KernelOptions structure to have more control over how BC7 codec is processing the blocks using CMP_ProcessTexture. This will include a BC7 mode mask that will allow users to specify using modes 5 to 7 for alpha channel blocks exclusively or only use a single mode 5 where alpha is 8 bits, additional options parameter may also be added to CMP_GenerateMIPLevels to improve the "sharpness" of the generated mip map levels prior to encoding.

That seems a good way to go. I will be on the look out for that commit or any new comment here.
Thanks for your hard work!

**Comment by NPCompress** [comment]
@andre-ferreira MIP map feature enhancements are underway in latest 4.1 release, The GUI allows choices for some filter types and more will be added. The API's will be updated to also allow these filters to be used and processed for MIP map generation.
