### ISSUE TITLE
Case mismatch in CMP_Core file

### ISSUE THREAD

**Issue by baldurk** [GPUOpen-Tools/compressonator#123]
Most of the CMP_Core files have consistent case e.g.: `BC1_Encode_kernel.cpp`, `BC2_Encode_kernel.cpp`, `BC5_Encode_kernel.cpp`, however the BC7 files have an uppercase K for the cpp and h: `BC7_Encode_Kernel.cpp`.

This isn't directly a problem, but can cause confusion integrating into a build on a case-sensitive system like linux, where it's easy to mistakenly assume all the files are named the same and get errors building the BC7 file. Renaming it to match would be a nice improvement to consider.

**Comment by NPCompress** [comment]
@baldurk  Done. Thx for the suggestion
