### ISSUE TITLE
Definition of CGU_INT8 not explicit

### ISSUE THREAD

**Issue by baldurk** [GPUOpen-Tools/compressonator#126]
On CPU the typedef for `CGU_INT8` is to a plain `char`:

https://github.com/GPUOpen-Tools/compressonator/blob/41ed90b803eb150584eda2e2739dc80bbe334804/CMP_Core/shaders/Common_Def.h#L260

But in C/C++ the signedness of `char` is implementation defined, it could be signed or unsigned.

I don't know if this actually causes any problems in the code, it depends if there's anywhere else that relies on CGU_INT8 having signed range when it might not. At first look I could only see places that were using it as effectively unsigned.

**Comment by NPCompress** [comment]
@baldurk  CGU_INT8 is used as a signed type in code where range is known in most cases to be positive in 0..128, and no larger. negative ranges for this type is not typically used in the code. all occurrence of CGU_INT8 in the code could have easily been replaced by CGU_UINT8 as negative values are not used!.
For code that requires unsigned values 0..255 CGU_UINT8 is explicitly defined.
