### ISSUE TITLE
How do I used this?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [GPUOpen-Tools/compressonator#127]
I've been in the documention, no lu9ck.
I just want to view the atc.dds files of Real Racing 3, but when I click on it, nothing happens. I want to conver them too.

**Comment by umustbeloggedintododat** [comment]
nevermind I got to view them but how do I convert them? I tried exporting the view but it is the wrong uv mapping

**Comment by umustbeloggedintododat** [comment]
I tried compressing them but I get 1 failed???? it is too vague

**Comment by umustbeloggedintododat** [comment]
nvm got it working but the results folder is empty?

**Comment by umustbeloggedintododat** [comment]
Nevermind about that, I was looking at wrong folder and got it working 📦

**Comment by umustbeloggedintododat** [comment]
Nevermind about that? the UV mapping doesn't work.

**Comment by NPCompress** [comment]
@umustbeloggedintododat  If possible, please provide a sample for testing,

**Comment by umustbeloggedintododat** [comment]
Nevermind, I have fixed it by rotating the result image 180 degrees and flipping it, now it maps correctly!

**Comment by NPCompress** [comment]
@umustbeloggedintododat  Glad you resolved the issue. Feel free to file any other issues or new features that needs our attention

**Comment by umustbeloggedintododat** [comment]
Nice, I used this app to convert the ATC.DDS file format which has no documentation on.
