### ISSUE TITLE
CLI: Inconsistent results between CPU and DXC encoding

### ISSUE THREAD

**Issue by StoneWolf** [GPUOpen-Tools/compressonator#128]
I'm using Compressonator v4.0.4855.
Following texture is the original PNG file:
![repro1](https://user-images.githubusercontent.com/422075/87595059-42981280-c6ee-11ea-9950-497e2f5eec02.PNG)
When compressing the image to DDS with the following command line:
`CompressonatorCLI.exe -fd BC7 -miplevels 20 "test_img26.png" "test_img26.dds"`
I get the expected results:
![repro2](https://user-images.githubusercontent.com/422075/87595087-4b88e400-c6ee-11ea-995e-2d235c1f8d48.PNG)
But when using DXC to encode the image with the following command line:
`CompressonatorCLI.exe -fd BC7 -miplevels 20 -EncodeWith DXC "test_img26.png" "test_img26.dds"`
Many artifacts appear at the transparent parts of the image, as seen in this picture:
![repro3](https://user-images.githubusercontent.com/422075/87595280-986cba80-c6ee-11ea-8cbd-fadff77267d9.PNG)

**Comment by NPCompress** [comment]
@StoneWolf Thank you for the images. This is a known issue as noted on the release Compressonator V4.0.4855 Features
Known issues and limitations: 
BC6 & BC7 on DX11 uses DirectX Tex shaders, CMP_Core version will be available soon.

Try using BC7 on OCL which should match more closely with the CPU version.

**Comment by StoneWolf** [comment]
Glad to know it's a known issue, thanks for the workaround, I'll just use the CPU version for now as this isn't a big deal for me. Thanks!

**Comment by NPCompress** [comment]
If your looking a high performance encoding and willing to loose a bit of quality (0.2dB to 0.5dB) try using this optimized "HPC" CPU version of the CMP_Core codecs.

CompressonatorCLI.exe -fd BC7 -miplevels 20 -EncodeWith HPC "test_img26.png" "test_img26.dds"

**Comment by StoneWolf** [comment]
@NPCompress Thanks, will use HPC.
