### ISSUE TITLE
Compressed Raw image data to PNG?

### ISSUE THREAD

**Issue by aboood40091** [GPUOpen-Tools/Compressonator#13]
I have some image data, compressed with BC3. (It's more like a dds file, but with no header)  
  
Can't I use Compressonator  to decompress it and convert it to PNG?

**Comment by xooiamd** [comment]
hi, you will need a dds file with proper header to do compression using the CLI or GUI app as a dds file must have the header structure https://msdn.microsoft.com/en-us/library/windows/desktop/bb943982(v=vs.85).aspx . A possible way for you is using only the compressonator SDK API with your own customized app that will load up your raw data file. You can use the sample project here https://github.com/GPUOpen-Tools/Compressonator/tree/master/Compressonator/Examples/VS2015 as reference.  You only need to call this function CMP_ConvertTexture(&srcTexture, &destTexture, &options, &CompressionCallback, NULL, NULL); to use the compressonator features. Hope this helps.

**Comment by aboood40091** [comment]
Well, I have already wrote my own dds writer yesterday since I had nothing else to do.

Thanks anyway.

**Comment by xooiamd** [comment]
Great, hope you enjoy using the compressonator and let us know if there is any issue. Thanks.

**Comment by aboood40091** [comment]
Thanks for this nice program. :)
#developers
