### ISSUE TITLE
Compressonator.H and CMP_Framework.h contain different KernelOptions

### ISSUE THREAD

**Issue by kingofthebongo2008** [GPUOpen-Tools/compressonator#131]
I experience crashes when i use CMP_Framework.h only
It differs with Compressonator.h

If i include both, i get compile time errors on Visual Studio 2019.
Making the definitions the same fixes the problem.
Why are they different?

**Comment by NPCompress** [comment]
@kingofthebongo2008  CMP_Framework.h is intended as a replacement for Compressonator.h that includes GPU supported codecs while Compressonator.h has only CPU based codecs definitions.

Current code supports VS2017, builds with VS2019 has not been fully verified.

**Comment by kingofthebongo2008** [comment]
This is correct, but framework used definition from the compressonator and
I got crashes in my example. I used only cmp framework. I had to recompile
the library locally to make it to work

**Comment by NPCompress** [comment]
@kingofthebongo2008 the common definitions of both headers are been cleaned up for v4.1
