### ISSUE TITLE
CMP_Save, CMP_Load does not work with dds

### ISSUE THREAD

**Issue by kingofthebongo2008** [GPUOpen-Tools/compressonator#132]
CMP_SaveTexture
CMP_LoadTexture with BC3 format restores format CMP_UNKOWN

**Comment by kingofthebongo2008** [comment]
This is in a DDS format

**Comment by kingofthebongo2008** [comment]
There reason probably is that you cannot load textures in many threads due to data loading.
one wants to use CMP_Framework because of the mipset

**Comment by kingofthebongo2008** [comment]
Actually CMP_Framework cannot load or save bc1, bc3 textures at all.
the example with DDS helpers can load and save them, but without the mipchains.

**Comment by NPCompress** [comment]
@kingofthebongo2008  The issue is been investigated. "Actually CMP_Framework cannot load or save bc1, bc3 textures at all."

Are you using your own code or using a modified example to test with?

**Comment by kingofthebongo2008** [comment]
Example 1. In the framework. I wanted to use the mipsets. The dds is
correct though.

**Comment by denislevesqueAMD** [comment]
This issue is pretty old and I haven't been able to replicate it with the little amount of information provided, so unless @kingofthebongo2008 still encounters the issue with the newest version this could probably be closed.

**Comment by NPCompress** [comment]
@kingofthebongo2008 Closing as issue resolved in latest release
