### ISSUE TITLE
BC7 encoder not thread safe

### ISSUE THREAD

**Issue by samojordan** [GPUOpen-Tools/compressonator#134]
We use CMP_ConvertTexture which is advertised as thread safe, but in the case of BC7 it's not. The problem is in BC7/shape.cpp. The function init_ramps() is called every time a conversion is executed. It fills static non-const arrays (shared between threads) in a non-atomic fashion by first initializing the arrays and then filling them with effectively const data. If a thread uses the data elsewhere while another thread is running through init_ramps(), crashes are likely to happen. We observed crashes in various places, such as BC7BlockEncoder::quant_single_point_d() which indeed uses one of those arrays. I haven't tested with latest github version but I haven't spotted significant changes in the relevant code, thus the problem may still be present.

**Comment by NPCompress** [comment]
@samojordan  The code should not be calling "init_ramps()" every time a conversion is executed", this should only occur once! and uses static non-const arrays when BC7BlockEncoder::quant_single_point_d() is called for quantization. As you are observing crashes in various places the issue will need to be investigated. 

There are 2 versions of the BC7 Codec (One that uses ramps and a newer version in CMP_Core that minimizes it on CPU and removes it when using GPU). The CMP_ConvertTexture call that uses the BC7 codec in CompressonatorLib, will be updated in a future release to use the CMP_Core version.

**Comment by samojordan** [comment]
"The code should not be calling "init_ramps()" every time a conversion is executed"

Indeed, but that's what happens right now if you execute CMP_ConvertTexture with multiple threads in parallel. Verified this with breakpoints, so this part should be easy to reproduce. The crashes I observed are *definitely* caused by init_ramps() being executed multiple times in parallel, there was always one of those arrays involved.

**Comment by samojordan** [comment]
I just noticed that there is a closed issue discussing thread-safety of CMP_ConvertTexture:

https://github.com/GPUOpen-Tools/Compressonator/issues/26

Apparently that issue was resolved by adding a mutex to Quant_Init(). init_ramps() should be mutexed as well. You could introduce a new function which calls both Quant_Init() and init_ramps() and add a single mutex which covers both.

**Comment by NPCompress** [comment]
@samojordan Fixed in upcoming release v4.1 - added 
void Quant_Init();
void Quant_DeInit();
