### ISSUE TITLE
Cannot load grayscale (8 bits) png files

### ISSUE THREAD

**Issue by trethaller** [GPUOpen-Tools/compressonator#136]
As of version 4.0.4855, loading a grayscale (8 bits) png file produces the following error: 
`Error: loading source image`

[Example image](https://user-images.githubusercontent.com/1499344/90020954-e1de0480-dcb0-11ea-8915-9b71ca6697c1.png)

Here are the image details coming from ImageMagick:
`PNG 1024x1024 1024x1024+0+0 8-bit Gray 256c 71872B 0.000u 0:00.005`

Some applications will automatically export grayscale pngs in this format.
Is this a know limitation?

**Comment by NPCompress** [comment]
@trethaller Thanks for the sample image. This is a new issue that needs to be fixed.

**Comment by trethaller** [comment]
Nice, thanks. For information the error also occurred on version 3.1.4064

**Comment by NPCompress** [comment]
@trethaller Fixed in upcoming release v4.1
