### ISSUE TITLE
Add KTX v2 Support

### ISSUE THREAD

**Issue by lexaknyazev** [GPUOpen-Tools/compressonator#137]
With the [KTX v2 specification](https://github.khronos.org/KTX-Specification/) being finalized, it would be great to support that container format in the Compressonator.

The [reference implementation (libKTX)](https://github.com/KhronosGroup/KTX-Software) includes full support for two Basis Universal codecs: ETC1S and UASTC with optional supercompression.

**Comment by NPCompress** [comment]
@lexaknyazev  Working on it already for v4.1. Used https://github.com/ux3d/glTF-Compressonator as merge and will be updating the code as referenced in LibKTX for Basis support which is already prototype into current source under USE_BASIS.

Compressonator_Lib uses Basis format as CMP_FORMAT_BASIS

**Comment by NPCompress** [comment]
@lexaknyazev Baseline ktx2 support added, code is been build from KTX lib master sources, additional features will be added as requested by users.
