### ISSUE TITLE
How do I add multiple destination settings for multiple files?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [GPUOpen-Tools/Compressonator#138]
So I am getting atc.dds files from Real Racing 3. I am converting them to ARGB 8888 PNG. How do I apply this same setting for all of them? I don't want to sit through converting them.,

**Comment by umustbeloggedintododat** [comment]
Now nothing happens when I press add dentation settings. F this program!

**Comment by NPCompress** [comment]
@umustbeloggedintododat Please try the following command line to convert the .dds files to .png using ARGB_8888 format.

**compressonatorcli -fx PNG -fd ARGB_8888 .\ddssrc .\pngdst**

The folders are local to the application. (to avoid know file search issues reported by other users)
**ddssrc**  folder contains all of the dds file you want to process
**pngdst** folder will contains files converted to png apended with _DDS_ARGB_8888.png

-fx sets the destination file extension
-fd set the channel format 

When viewing the results on say Visual Studio or some other paint tools, the resulting channel format may show as 32bpp BGRA

(Optionally you can filter the source files by only processing specific file sources using -fs command. example if you have .ktx file mixed in with .dds file and want to process only ktx files to png add the command -fs KTX)

If you want to remove all of the appended _DDS_ARGB_8888 from the files converted, go the destination folder using "Windows File Explorer" and then do a "Windows PowerShell" (shift key + right mouse-click in a folder and select "Open PowerShell in this Folder") and type this command, with an enter key when done to run it:

get-childitem *.png | foreach { rename-item $_ $_.Name.Replace("_DDS_ARGB_8888", "") }

As shown:

![image](https://user-images.githubusercontent.com/18406717/90806613-3e61a500-e2eb-11ea-83cc-e608ae4c857e.png)

**Comment by umustbeloggedintododat** [comment]
'compressonatorcli' is not recognized as an internal or external command,
operable program or batch file.

**Comment by umustbeloggedintododat** [comment]
nvm I figured it out lol

**Comment by NPCompress** [comment]
@umustbeloggedintododat  Are you using this command line application installation?
CompressonatorCLI_x64_4.0.4855.exe

**Comment by umustbeloggedintododat** [comment]
I ran it in the compressanotercli folder and it worked
