### ISSUE TITLE
Allow chosing installation path

### ISSUE THREAD

**Issue by LtdJorge** [GPUOpen-Tools/compressonator#142]
It would be great if we could choose the installation path, specially for users with multiple drives.

**Comment by NPCompress** [comment]
@LtdJorge  There is an installation folder tab that allows you to select another folder as shown, just click on it and you will be presented to select where you want to do the installation.

![image](https://user-images.githubusercontent.com/18406717/93672401-8f92bf00-fa78-11ea-9442-13ddab9923f2.png)


![image](https://user-images.githubusercontent.com/18406717/93672426-ba7d1300-fa78-11ea-8cda-11eb5b8ccf15.png)
