### ISSUE TITLE
ETC.DDS messes up color info?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [GPUOpen-Tools/compressonator#144]
So I am trying to convert the ETC.DDS for Real Racing 3, except I don't think it is supposed to be in these colors:
![2019_porsche_935_ext_3 etc_dds_ARGB_8888](https://user-images.githubusercontent.com/54049600/95641752-12081080-0a72-11eb-80cf-dc014bff60f7.png)
I think this is what it's supposed to look like:
https://vignette.wikia.nocookie.net/rr3/images/5/5e/Porsche_935_2019_3.jpg/revision/latest?cb=20201006023720
So how do I fix this odd texture error?

**Comment by umustbeloggedintododat** [comment]
Help, I tried adding -doswizzle to my command and the folder is empty now, no converted texture.
`compressonatorcli.exe -doswizzle -fx PNG -fd ARGB_8888 .\ddssrc .\pngdst`

**Comment by umustbeloggedintododat** [comment]
ACTUALLY I found out the problem. The R and B channels are swapped. They're RGB instead of BGR, a Paint.net plugin fixed this!
But how do I do this included with my compressonator command?
`compressonatorcli -fx PNG -fd ARGB_8888 .\ddssrc .\pngdst`

**Comment by NPCompress** [comment]
@umustbeloggedintododat  The command line you used is the correct way to transcode sources to RGB format. 

compressonatorcli -fx PNG -fd ARGB_8888 .\ddssrc .\pngdst

Must be a bug in specifying the -fx format properly to the save target image code (which is a Qt image save API for PNG file formats).

**Comment by NavNTCMP** [comment]
@umustbeloggedintododat  Issue addressed in v4.5 release
