### ISSUE TITLE
Compressonator not recongizing these files?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [GPUOpen-Tools/compressonator#146]
All I get is this generic error:
_Error [4]: DDS Plugin Failed to load texture file C:/Compressonator_4.0.4855/bin/CLI/ddssrc/2016_alfa_romeo_giulietta_tcr_badges.etc.dds_
It recgonizes the other textures.I checked them in a hex editor and they appear to use the same file structure. How do I fix this???????????
http://www.mediafire.com/file/t8cofmoodtiu6j7/2016_alfa_romeo_giulietta_tcr_wheel_blur.etc.dds/file

http://www.mediafire.com/file/4xvpatz4dfym66i/2016_alfa_romeo_giulietta_tcr_badges.etc.dds/file

**Comment by umustbeloggedintododat** [comment]
Help?

**Comment by umustbeloggedintododat** [comment]
HELP?

**Comment by umustbeloggedintododat** [comment]
HELP???

**Comment by NPCompress** [comment]
@umustbeloggedintododat  Sorry to hear that you are having issues with those files, Will be looking at them and run tests to determine the stored data formats.

**Comment by umustbeloggedintododat** [comment]
Alrighty.

**Comment by umustbeloggedintododat** [comment]
It's been an hour. Are the tests done yet?

**Comment by NPCompress** [comment]
@umustbeloggedintododat  Building v4.0 GU and CLI release from source, will take a while to setup and debug.

**Comment by umustbeloggedintododat** [comment]
Ok.

**Comment by umustbeloggedintododat** [comment]
I'm a Windows person and I don't know what you said?

**Comment by NPCompress** [comment]
@looks like the color channel formats are set for 16 bit each in the samples. Our DDS loader code checks only for for a limited combination 16 bit source formats.  I will see if new code can be added to attempt to load this file and get a view of it in the GUI app.

**Comment by umustbeloggedintododat** [comment]
Thanks, it won't convert too.

**Comment by NPCompress** [comment]
@umustbeloggedintododat  You labeled these files as ETC dds files. Are these suppose to be compressed ETC compressed images, The DDS file FourCC signatures are blank.  Seem like these files are custom build.

**Comment by umustbeloggedintododat** [comment]
Yeah, they're ETC.DDS files.

**Comment by umustbeloggedintododat** [comment]
They were decompressed out of _etc.dds.z_ files from _Real Racing 3._

**Comment by NPCompress** [comment]
What did you use to decompress them?

**Comment by umustbeloggedintododat** [comment]
QuickBMS script.

**Comment by NPCompress** [comment]
The sample files are not readable even with apps like (Paint+, DirectXTex DDSView and Visual Studio). Not much can be done to fix this in CMP DDS code.

**Comment by umustbeloggedintododat** [comment]
Aww well that sucks, I can't find a fix to this cause all I could find was a forum post about the this format but it had no help. :(

**Comment by umustbeloggedintododat** [comment]
Is there any other way to decompress/convert this to a readable file? The ATC.DDS files I've worked with before aren't readable with apps but Compressonator can read them.

**Comment by NPCompress** [comment]
@umustbeloggedintododat  It would take a lot of effort to decode those file. Its seems like there is not easy way to do this, Perhaps the script authur(s) at http://quickbms.aluigi.org can help with a proper fix to save the files into a proper dds file format.

**Comment by umustbeloggedintododat** [comment]
Sadly I'm not a coder so I'm not too sure on what to do.

**Comment by umustbeloggedintododat** [comment]
And the script is made for extracting the files, not converting files. By _decompress_ I meant _extract the vehicle texture from the archive._

**Comment by umustbeloggedintododat** [comment]
Anybody )else?

**Comment by umustbeloggedintododat** [comment]
Bumping to see if this can be fixed

**Comment by umustbeloggedintododat** [comment]
Help? I need this fixed quick.

**Comment by umustbeloggedintododat** [comment]
The quickbms is for extracting the files, not decompressing them.

**Comment by umustbeloggedintododat** [comment]
Problem solved here: 
https://forum.xentax.com/viewtopic.php?f=16&t=22818&p=167675#p167675

**Comment by NPCompress** [comment]
@umustbeloggedintododat  Nice, can you attach the dds files generated here. Thx

**Comment by umustbeloggedintododat** [comment]
![badges](https://user-images.githubusercontent.com/54049600/96151492-70514b00-0ed9-11eb-8cb5-f0ca45101a5d.png)
![wheel blur](https://user-images.githubusercontent.com/54049600/96151496-70e9e180-0ed9-11eb-812e-0137d40acee5.png)
They're in png

**Comment by NPCompress** [comment]
@umustbeloggedintododat  We can close this issue!

**Comment by umustbeloggedintododat** [comment]
What's odd is that my 3D modeling program (Blender) can recognize these. They're flipped vertically though so they have virtually no use. Strangely enough, it recognizes the broken ones.
