### ISSUE TITLE
How to correctly use CMP_Framework with CMake

### ISSUE THREAD

**Issue by LtdJorge** [GPUOpen-Tools/compressonator#148]
I'm writing a program that makes use of the Framework, but CMake is giving me a hard time. I don't know what needs to be done on my side so that CMake builds CMP_Framework alongside my target, and links against it.

**Comment by NPCompress** [comment]
@LtdJorge  We will be posting a new update for a the code using updated cmakes soon. What platform are you building on Windows or Linux?

**Comment by NPCompress** [comment]
@LtdJorge For windows we have VS2017 project files for CMP_Framework you can use.

**Comment by LtdJorge** [comment]
Yes, sorry, my bad. I am on Windows, using Visual Studio 16 2019 and with Ninja generator. The thing is I am using CLion because it's a lot faster than VS for me. So I need CMake. All my other dependencies use CMake too.

**Comment by NPCompress** [comment]
@LtdJorge  Try this, backup the old cmakelist.txt in CMP_Framework and then use this one attched in you builds. You might need to adjust some of the content if needed for your use case. Its setup for the new  pending update!

[CMakeLists.txt](https://github.com/GPUOpen-Tools/compressonator/files/5447724/CMakeLists.txt)

**Comment by LtdJorge** [comment]
Thanks, it worked. However, I'm not sure what is the best way to load CMP_Framework on my project, as I feel my current way is very hacky. Do I have to use 
```
target_link_libraries
```
or any other CMake directive?

**Comment by NPCompress** [comment]
@LtdJorge  The current implementation is best and used in v4.1

**Comment by LtdJorge** [comment]
Thanks, Navin!
