### ISSUE TITLE
Inconsistency between interpretation of ARGB_8888 between BC1 and BC7

### ISSUE THREAD

**Issue by subb** [GPUOpen-Tools/Compressonator#15]
When using a buffer of uint32 as a source texture, compressing that texture to BC7 gives a texture with its red and blue channels mixed up. Using the same source texture and compressing it to BC1 (and possibly BC2 and BC3) gives the correct result.

The input buffer has each pixel encoded as a uint32, with the following format : 0xAARRGGBB. Note that this is stored in memory as BB GG RR AA (little endian). This buffer is casted to a CMP_BYTE\* and passed to CMP_ConvertTexture through a CMP_Texture struct with the CMP_FORMAT_ARGB_8888 format.

When compressing this texture to a BC1, the compressor casts the CMP_BYTE buffer to a DWORD buffer (CCodec_DXTC::CompressRGBBlock, line 110), and bitmasks each dword to extract channels information (ex. CompressonatorXCodec.cpp, line 2333). This respect the ARGB channel ordering.

When compressing this texture to a BC7, the compressor directly read the CMP_BYTE buffer and interpret the channels as they appear in memory (Codec_BC7.cpp, line 542). It effectively reads BGRA, but interpret it has RGBA. This is not consistent with the BC1 codec.

There's also seems to be a confusion between the internal and external API relative to the placement of the alpha channel. Fro example, there's CMP_FORMAT_ARGB_8888, but CCodecBuffer_RGBA8888 and no conversion is done when passing the data of a ARGB texture to the RGBA codec.

Is this a known issue or am I missing something?

**Comment by NPCompress** [comment]
Hi Subb,

You are not missing something, the SDK code original developed for BC1 to BC5 (DXT1..DXT5), ATI1 and ATI2. expect source data as BGRA, Newer codecs changed the ordering for BC7 and BC6H in reverse order RGBA.

There is much confusion when handling multiple codecs requiring swizzle operations from original image sources and destination codecs.

For now input sources has to be cased accordingly with respect to the destination codec. 
When passing down to the compression API - data is expected to be RGBA and switch to fix the spacial cases.

All codecs should be consistent with the RGBA input and respect format definitions such as you pointed out for CMP_FORMAT_ARGB_8888, these changes are forthcoming and will take time to clean out.

**Comment by NPCompress** [comment]
Partial fix in V2.4. Fix with new channel mapping will be available in V2.5
