### ISSUE TITLE
RGB or BGR as input in V3.2

### ISSUE THREAD

**Issue by xiazhibin** [GPUOpen-Tools/compressonator#152]
From this issue: [R and B channels are switched for ETC_RGB compression](https://github.com/GPUOpen-Tools/compressonator/issues/34)

In V2.4, ETC ... are expecting image source as BGR as input.

Now in V3.2, Do image source change to RGB as input?

**Comment by NPCompress** [comment]
@xiazhibin Compression sdk is expecting RGBA as input to the compressor this was changed since v3.2 and is used this way up to v4.1.

ETC processing needs to be reviewed as there are still a number of open issues still to be fixed related to sizzled R and B channels.

**Comment by xiazhibin** [comment]
Thanks
