### ISSUE TITLE
QImage::Format_RGBX64 seems supported but is disabled in QImage2MIPS

### ISSUE THREAD

**Issue by StoneWolf** [GPUOpen-Tools/compressonator#153]
I was trying to convert [this](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/ToyCar/glTF/Fabric_normal.png) image to DDS with the CLI (with the following command line: `-fd BC7 -miplevels 20 -EncodeWith GPU input.png output.dds`) but got the error "Error: loading source file!". So I cloned the repository, compiled the CLI and debugged it, and I noticed that the function QImage2MIPS (in file applications\\_plugins\common\mipstoqimage.cpp, line 168) restricts the input QImage to certain formats only. I tried disabling the check altogether and to my surprise, the conversion to DDS was successful.

Is there any reason for the QImage format RGBX64 to be disallowed?

**Comment by NPCompress** [comment]
@StoneWolf  Nice to know that you have it working. You are correct the code may work without the restriction placed on that API. The reason for the restriction is that sections of the code and other transcoding APIs is been reworked to use the Compressonator SDK codec buffer classes to allow a wider range of format transcodes for the code used in Qt, stbi_image, etc... 
The DDS file IO is also been reworked to support these SDK codec converters. 
This should significantly clean up and remove code duplications used throughout the CLI and GUI code.

**Comment by StoneWolf** [comment]
Got it.
Thanks for the quick answer by the way. Should I close this issue since you are aware of the behavior?

**Comment by NPCompress** [comment]
@StoneWolf Yes please.
