### ISSUE TITLE
build v3.2 in linux

### ISSUE THREAD

**Issue by xiazhibin** [GPUOpen-Tools/compressonator#154]
Since some files remove in v3.2, I found that I can't build the source with the Instructions.[build_instructions](https://github.com/GPUOpen-Tools/compressonator/blob/v3.2.4691/docs/source/build_from_source/build_instructions.rst)

For example, `cd ../../_Plugins/CImage/DDS/Make/`, the `Make` folder was removed! And in v2.7,  the `Make` folder is still here 

So, how can I build the source?

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
