### ISSUE TITLE
CompressonatorCLI -Performance Command (Still) Invalid

### ISSUE THREAD

**Issue by BigheadSMZ** [GPUOpen-Tools/compressonator#155]
Going back to this issue from a few months back:
https://github.com/GPUOpen-Tools/compressonator/issues/140

I just downloaded Compressonator V4.1.5083 CLI and it's still there.

Option [-Performance] : Command option is invalid
Invalid Command

A comment on that issue mentioned it was fixed in the source back on September 30th which predates the most recent release. I assumed it would be fixed in the latest release, unfortunately I'm still not able to use this command.

**Comment by BigheadSMZ** [comment]
Any ETA when this will make it into an official release? The last version that works with "-Performance" is all the way back in v3.0.3707. It makes a huge difference when trying to maximize quality vs. time when creating BC7 textures. For now I have been suggesting users to use that for now.

My script makes use of both "-Quality" and "-Performance", calculating different values depending on image dimensions. For example: smaller textures get values that take longer to encode but get higher quality, larger textures get values that are faster where quality isn't usually as important. Without the performance command, I would have to rebalance all '-Quality' to exclude it. But of course I'd rather wait for it to be fixed officially. 👍

**Comment by NPCompress** [comment]
@BigheadSMZ  Fix is in the current master source branch.  #155 & #156 , Release binaries are expected for late Q2.

**Comment by BigheadSMZ** [comment]
Just wanted to say this issue is finally fixed once and for all. Thank you so much!
