### ISSUE TITLE
CompressonatorCLI -nomipmap Command Conflict

### ISSUE THREAD

**Issue by BigheadSMZ** [GPUOpen-Tools/compressonator#156]
In the latest version (V4.1.5083) CLI, the "-nomipmap" command no longer works in that it reports that it is conflicting with the "-miplevels" command even when it is not set. Simply using just -nomipmap gives this error and the image is not created:

Both nomipmap and miplevels are set!

Edit: Just to throw it out there if anyone else has the same issue, just using "-miplevels 1" is a workaround for now so that you won't have to manually eliminate mipmaps if they are not desired.

**Comment by BigheadSMZ** [comment]
Also wanted to pop into this one and say that this issue is also resolved. Thank you so much!

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
