### ISSUE TITLE
CompressonatorGUI  4.1.5083 - MipMap generation not working

### ISSUE THREAD

**Issue by nbonniere** [GPUOpen-Tools/compressonator#157]
CompressonatorGUI  4.1.5083

Error [11]: D3DXFilter Plugin Load D3DX failed
Error in processing MipMap!

Tried CompressonatorCLI and mipmaps were generated OK.

**Comment by NPCompress** [comment]
@nbonniere  This error suggests that some DirectX components is not installed for use in the GUI, Try installing DirectX user runtimes https://www.microsoft.com/en-ca/download/details.aspx?id=8109

**Comment by nbonniere** [comment]
Perhaps, and I can try, but if the application requires an older DirectX component not installed by Win10, then perhaps it should include this missing component, or be adjusted to using current DirectX components.

**Comment by nbonniere** [comment]
Tried, but package just has CAB files from 2005 to 2010. Tried d3dx_43 CAB from 2010, but no go.

Error message is about D3DXFilter Plugin, and PlugIn kind of implies it has been added for Compressonator, (???)

**Comment by NPCompress** [comment]
@nbonniere, the code for mipmap filters (D3DX point..., D3DX Box) is using DirectX 9 API. The code does need adjustment to use current DirectX. When installing the GUI, the installer tries to auto detected features, if these components are not installed it should display an option to install them.

The MipMap plugin (Image_MipMap.dll) is in the folder C:\Compressonator_4.1.5083\bin\GUI\plugins. It will search for any (D3DX9_24 to D3DX9_41) dll's in the windows folders or system paths when loaded by the GUI app.

**Comment by nbonniere** [comment]
OK, I installed ALL instead of just D3Dx_43, and it is now working. Thank you.
However, installing all these files seems an overkill.

**Comment by nbonniere** [comment]
The CLI version does generate mipmaps and did NOT require the 2010 DirectX redistributable components. The CLI version has the same image_mipmap.dll and yet it did NOT need the D3Dx dlls to generate mipmaps. Why does the GUI version need the D3Dx dlls ?

**Comment by NPCompress** [comment]
@nbonniere  The GUI version is using specialized DirectX mipmap filters based on specific algorithms to optimize image MIP levels  for various type of images sources (text, photo, graphic etc..), this feature is not enabled in the CLI version which only uses a CPU based Box Filter for generating MIP levels. In future versions of CLI (Windows Version) users will have options to set these filters.

Reference Info: https://docs.microsoft.com/en-us/windows/win32/direct3d9/d3dx-filter

**Comment by nbonniere** [comment]
I understand. Thank you.
