### ISSUE TITLE
Build bat files don't work if the dir containing them is called "Compressonator"

### ISSUE THREAD

**Issue by suikki** [GPUOpen-Tools/Compressonator#16]
Also that's the default dir name when cloning from github so it's pretty bad.

The reason is that the batch file first sets the correct root dir:
`IF EXIST %BatchDir%\Compressonator     (set COMPRESSONATOR_ROOT=%CD%\Compressonator)`

But a couple lines after that also finds this wrong dir:
`IF EXIST %BatchDir%\..\Compressonator  (set COMPRESSONATOR_ROOT=%CD%\..\Compressonator)`

**Comment by NPCompress** [comment]
The seconds line is been used in some cases for test automation, where batch file is duplicated in the compressonator sub folder. 

The second instance of the build batch files can be removed. The batch files will be updated today
