### ISSUE TITLE
question about miplevel generation 

### ISSUE THREAD

**Issue by xiazhibin** [GPUOpen-Tools/compressonator#160]
------------------------------------------------
CompressonatorCLI V3.2.535 Copyright AMD 2019
------------------------------------------------

I have 512 x 512 png and call CLI with this command

```
CompressonatorCLI -fd ASTC -miplevels 1 512.png output.ktx
```

the output is 

```
Source Texture size = 1048576 Bytes, width = 512 px  height = 512 px
Destination Texture size = 262144 Bytes   Resulting compression ratio = 4.00:1
Processing progress = 100
```

------------------------

And then this command

```
CompressonatorCLI -fd ASTC -miplevels 2 512.png output.ktx
```

the output is 

```
Source Texture size = 1048576 Bytes, width = 512 px  height = 512 px
Destination Texture size = 262144 Bytes   Resulting compression ratio = 4.00:1
Processing progress = 100
Source Texture size = 262144 Bytes, width = 256 px  height = 256 px
Destination Texture size = 65536 Bytes   Resulting compression ratio = 4.00:1
Processing progress = 100
Source Texture size = 65536 Bytes, width = 128 px  height = 128 px
Destination Texture size = 16384 Bytes   Resulting compression ratio = 4.00:1
Processing progress = 100Done Processing
```

----------

My question is

- why miplevel 1 generates 512px but not 256 px
- why miplevel 2 generates 512 px, 256 px, 128 px but not 256 px,128px

Is that a bug about the output?

**Comment by NPCompress** [comment]
@xiazhibin This is a bug in V3.2.535, there is no fix for this in that release. 
Current working master source is 4.2.x and release branch is at v4.1.5083,  which has this output issue fixed.

Sample result using latest release:
![image](https://user-images.githubusercontent.com/18406717/104765606-288bcb00-5737-11eb-8bba-40da87e0552e.png)

**Comment by xiazhibin** [comment]
thanks @NPCompress ! 
And I find that the `-Quality <value>` option can also control the quality of ASTC, bug the Doc says that it just works for `BC7`。

**Comment by NPCompress** [comment]
@xiazhibin  Thanks will correct the documentation.

**Comment by xiazhibin** [comment]
thanks
