### ISSUE TITLE
how to build at VS2019??

### ISSUE THREAD

**Issue by SungJJinKang** [GPUOpen-Tools/compressonator#162]
my project is on VS2019. 
but i have been trying build on VS2019. but it doesn't works.
this library doesn't support VS2019??

**Comment by NPCompress** [comment]
@SungJJinKang  Here is a sample modified batch file to run on the root folder where we VSBuild.bat

set QT5_DIR=C:\Qt\Qt5.12.6\5.12.6\msvc2017_64
set VULKAN_SDK=C:\VulkanSDK\1.2.141.2

set CurrDir=%CD%
for %%* in (.) do set CurrDirName=%%~nx*
IF EXIST %CurrDir%\build (rmdir build /s /q)
mkdir build 

REM --------------------------------------------------------
REM Get Common folder content: works only for Git repo
REM --------------------------------------------------------
python %CurrDir%\scripts\fetch_dependencies.py

cd build
cmake -G "Visual Studio 16 2019" ..\..\%CurrDirName%
cd %CurrDir%

**Comment by NPCompress** [comment]
@SungJJinKang  You will have to rebuild / update cmake for one of the external common Libs (KTX) for VS2019 prior to running the updated VSBuild.bat file. The VS2017 libs folder should be easy to convert to 2019 project files. 

Currently all external libs in common have mix binary libs supporting VS2017 and VS2019, They should all work with your 2019 project files with no issues.
