### ISSUE TITLE
CLI, DDS>TGA???

### ISSUE THREAD

**Issue by umustbeloggedintododat** [GPUOpen-Tools/compressonator#166]
How do I convert a DDS to TGA using the cli????????????

**Comment by umustbeloggedintododat** [comment]
Sorry I've should've elaborated , I meant how do I batch convert multiple DDS files to TGA using the CLI?

**Comment by NPCompress** [comment]
@umustbeloggedintododat There is a bug in the code which fails to generate destination files and is scheduled for a fix in v4.3 release. 
This is the command line syntax to run  transcode from dds files in a images folder  to tga files in results folder
compressonatorcli -fd ARGB_8888 -ff DDS -fx TGA  ./images  ./results

When a fix is available in source it will be posted. 
Windows CLI is built when source is updated so you can try the changes before official release. Look at https://github.com/GPUOpen-Tools/compressonator/actions for latest build and click on it then download the built zip file to try.

**Comment by umustbeloggedintododat** [comment]
Still not working :/

**Comment by umustbeloggedintododat** [comment]
My mistake, it works, it just generates in the root drive for some reason.
