### ISSUE TITLE
Last two releases have wrong version name in tar file for Linux CLI

### ISSUE THREAD

**Issue by ShukantPal** [GPUOpen-Tools/compressonator#169]
For example, in Compressonator 4.2.5185 the .tar.gz file ends with 4.2.5150 - which is problematic if you want to fetch based a $VERSION variable in the CI. The Windows files don't have this issue.

**Comment by NPCompress** [comment]
@ShukantPal  Noted. and will be updated thanks.

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
