### ISSUE TITLE
build.sh referencing non-existent External directory

### ISSUE THREAD

**Issue by ShukantPal** [GPUOpen-Tools/compressonator#170]
https://github.com/GPUOpen-Tools/compressonator/blob/cb281b97eb05e35ec739a462c71524c4b1eefae3/scripts/build.sh#L7

Should probably be `${COMPRESSONATOR_PROJECT_DIR}/external/build `, since the top-level directory `External` is actually `external` now.

**Comment by ShukantPal** [comment]
I get https://github.com/GPUOpen-Tools/compressonator/blob/cb281b97eb05e35ec739a462c71524c4b1eefae3/scripts/build.sh#L40

> #16 0.210 + cmake /trees/Compressonator/External/cmake -DCOMPRESSONATOR_PROJECT_DIR:STRING=/trees/Compressonator -DCMAKE_BUILD_TYPE:STRING=Release -DCLEAN_BUILD:BOOL=OFF
#16 0.258 CMake Error: The source directory "/trees/Compressonator/External/cmake" does not exist.

**Comment by NavNTCMP** [comment]
@ShukantPal  Issue addressed in v4.5 release
