### ISSUE TITLE
BC7 encoding with Compressonator SDK prints "Err: requantized_image_err"

### ISSUE THREAD

**Issue by ShukantPal** [GPUOpen-Tools/compressonator#176]
If I use the Compressonator CLI, BC7 encoding works perfectly fine. However, I'm now using the Compressonator SDK with JNI bindings to Java. When I run `CMP_ProcessTexture` with BC7 encoding, the following is printed for almost 100K times.

```
Err: requantized_image_err
```

**Comment by ShukantPal** [comment]
Note that the output is perfectly fine and the destination texture gets saved successfully.

**Comment by NPCompress** [comment]
@ShukantPal  This build setup is new and never tested with JNI. Interesting that this error is generated, its indicating that a large number of 4x4 processed blocks are not been re-quantized in (shake() call) for better quality.

You say "Note that the output is perfectly fine and the destination texture gets saved successfully." is the PSNR high when compared to the original file?

**Comment by ShukantPal** [comment]
Not sure, but the files did have lots of "errors" (solid color pixels that looked like they had the wrong value)

**Comment by NPCompress** [comment]
@ShukantPal  That is the expected result for this type of err, something failed in processing the block in either the shake() or initial setting in BC7 options like errorThreshold  value is not set to a valid range.

**Comment by ShukantPal** [comment]
I didn't set any errorThreshold value in my code. Are you talking about the kernel options?

**Comment by NPCompress** [comment]
@ShukantPal Yes, ref framework_example2.cpp for a BC7  example

**Comment by ShukantPal** [comment]
Will look into it - I would suggest to have sensible defaults in this case (in the constructor?)

**Comment by NPCompress** [comment]
@NPCompress It has defaults, but can be overwritten by user setting passed down in CMP_ProcessTexture. Will add additional parameter check for valid ranges. This however may not be the root cause of the issue reported and calls inside the code for BC7 shake() needs to be debugged using your setup environment.

**Comment by NPCompress** [comment]
Please review your JNI with latest release
