### ISSUE TITLE
CLI: FX option not documented.

### ISSUE THREAD

**Issue by EatThePath** [GPUOpen-Tools/compressonator#180]
I scoured the documentation today trying to find how to specify the output file format in a batch conversion, and found no sign at all of it. I found the `-fx` option by looking around this issue tracker, and it resolved that issue, but it really ought to be documented somewhere

**Comment by ymmikhail** [comment]
Thanks, we'll add this option to the documentation

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
