### ISSUE TITLE
framework: 16-bit png not supported

### ISSUE THREAD

**Issue by seragh** [GPUOpen-Tools/compressonator#181]
Can't load 16 bit png using framework for processing.

file command identifies them as:
PNG image data, 1024 x 1024, 16-bit/color RGB, non-interlaced
PNG image data, 1024 x 1024, 16-bit grayscale, non-interlaced

**Comment by seragh** [comment]
The release notes claim this to be fixed, but can't confirm, getting CMP_ERR_UNSUPPORTED_SOURCE_FORMAT

Looking at the source tree there is a copy of stb_image-2.08 but initial 16-bit png support was only added in 2.11

**Comment by NPCompress** [comment]
@seragh Thanks for bringing this to our attention. This issues is not resolved and as you suggested a new lib build with latest stb_image will fix this for the call into Framework lib CMP_LoadTexture ,  The 16 bit support is for Qt code in CMP_CreateQImage that is  called by AMDLoadMIPSTextureImage in the CLI and GUI applications.

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4

**Comment by seragh** [comment]
Confirmed, thanks
