### ISSUE TITLE
framework: fails to load already compressed dds

### ISSUE THREAD

**Issue by seragh** [GPUOpen-Tools/compressonator#183]
For the sake of mipmaping would be nice to be able to open those old textures.

file command identifies them as:
Microsoft DirectDraw Surface (DDS): 16 x 16, compressed using DXT1
Microsoft DirectDraw Surface (DDS): 128 x 128, compressed using DXT3
Microsoft DirectDraw Surface (DDS): 512 x 512, compressed using DXT5

**Comment by ymmikhail** [comment]
Hi @seragh, thanks for the report. Will look into this issue.

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4

**Comment by seragh** [comment]
While it's possible to load them now, they can't be processed.

Calling CMP_GenerateMIPLevels results in
`
cmp_framework/common/cmp_mips.cpp:1046: bool CMP_CMIPS::AllocateMipLevelData(CMP_MipLevel*, int, int, CMP_ChannelFormat, TextureDataType): Assertion '0' failed.
`
