### ISSUE TITLE
CompressonatorCLI GenGPUMipMaps option is broken

### ISSUE THREAD

**Issue by j-cano** [GPUOpen-Tools/compressonator#185]
Hi,

Using CLI version **4.2.5185**.

The following command

**compressonatorcli.exe -miplevels 3 -fd BC1 -EncodeWith GPU test\001gscm00.bmp test\001gscm00_nogpumipmaps.dds**

generates a file with 4 mipmap levels (original resolution + 3). Everything ok.

The next command

**compressonatorcli.exe -miplevels 3 -fd BC1 -EncodeWith GPU -GenGPUMipMaps test\001gscm00.bmp test\001gscm00.dds**

generates a file with 3 mipmap levels (original resolution + 2) and both low resolution levels are empty.
Also note the final number of levels is different with the option activated.

One additional minor issue, the usage of compressonatorcli.exe says

**-GenGPUMipMap**             When encoding with GPU this flag will enable mipmap level generation
                          using GPU HW. **Default level is 1 unless miplevels is set**

There is a missing "s" at the end of the option, the working one is "GenGPUMipMap**s**" and what "Default level is 1..." means? There are no levels to specify with this option, right?

Thanks.

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
