### ISSUE TITLE
CLI: Bulk operations not working as expected on windows 10

### ISSUE THREAD

**Issue by EatThePath** [GPUOpen-Tools/compressonator#186]
Either I am deeply, deeply misunderstanding something or the path specification for handling multiple files at once is misbehaving.
From the documentation I expected that if I have `D:\textures\in\A.tga` and I make a CLI call from `textures` with all the appropriate other inputs and `./in/ ./out/` I will end up with `D:\textures\out\A.dds`. That has not been my experience. In my experience that just finds nothing and does nothing.

Trial and error led me to the form of `.\in .\out`, which found the input but then saved outputs in the drive root.

`.\in D:\textures\out` gets a little closer, it results in the creation of `D:\textures\A.dds` close but no cigar.

What I have ended up actually using is `.\in D:\textures\out\dummy\` which successfully creates `D:\textures\out\A.dds`. It also creates the `dummy` subfolder, and puts nothing in it.

Meanwhile, if I deal with single files, such as calling `.\in\a.tga .\out\a.dds`, it works fine.

I hope that's enough information to go off of, if not I'll do my best to help nail it down.

**Comment by ymmikhail** [comment]
@EatThePath Thanks for reporting this issue, it will be fixed in v4.3
