### ISSUE TITLE
Compressonator can't open tga file

### ISSUE THREAD

**Issue by Andreyogld3d** [GPUOpen-Tools/compressonator#190]
Compressonator can open tga file

[image file.zip](https://github.com/GPUOpen-Tools/compressonator/files/7464231/image.file.zip)

![image](https://user-images.githubusercontent.com/8597425/139958288-ad4e0f92-d019-4875-9e6d-131555d3a478.png)

but this file can be opened using Visual Studio or RenderDoc
![image](https://user-images.githubusercontent.com/8597425/139959294-bb3d445f-4b24-48ba-8792-f29fc01f931a.png)

**Comment by ymmikhail** [comment]
@Andreyogld3d This image is in Mono format, which is currently not yet supported in Compressonator,

**Comment by NPCompress** [comment]
@Andreyogld3d  TGA Mono format is now supported in latest release
![image](https://user-images.githubusercontent.com/18406717/218477500-f3e2af4a-f8c1-468b-b2df-90093d13e99b.png)

**Comment by Andreyogld3d** [comment]
Thanks!
