### ISSUE TITLE
Compressonator can't open dds file

### ISSUE THREAD

**Issue by Andreyogld3d** [GPUOpen-Tools/compressonator#191]
[particle_smoke.dds.zip](https://github.com/GPUOpen-Tools/compressonator/files/7464277/particle_smoke.dds.zip)

![image](https://user-images.githubusercontent.com/8597425/139959095-c692049a-db58-4a27-afc8-18c5fdea29f1.png)

but, this file can be opened using Visual Studio 

![image](https://user-images.githubusercontent.com/8597425/139959174-36c7f29d-bb0b-4725-99e0-38b870817912.png)

**Comment by ymmikhail** [comment]
Hi @Andreyogld3d, the image you shared seemed to open fine on my end. Could you describe what happens after you click the thumbnail next to the file name, such any errors or messages?

Also, is this on the current latest version (4.2.5185)? If not, please try the latest version and let me know if this resolves your issue. Thanks!

**Comment by Andreyogld3d** [comment]
hi @ymmikhail, Yes I use 4.2.5185 version.

I cannot reproduce a current issue, But I have a new bug - crash during Generation MIP maps after press button  -  сompressonator stops your works without any Error messages. Should I create a new issue or I can rename current ?

![image](https://user-images.githubusercontent.com/8597425/153224379-aaedf79b-8b41-4ec8-beb2-a57b169c7403.png)

**Comment by NPCompress** [comment]
@Andreyogld3d  You can close the current issue and create a new one,

**Comment by Andreyogld3d** [comment]
@NPCompress Hi,
new issue https://github.com/GPUOpen-Tools/compressonator/issues/202
