### ISSUE TITLE
CLI cannot process 16-bit PNG files [4.2.5185]

### ISSUE THREAD

**Issue by sherief** [GPUOpen-Tools/compressonator#194]
I tried compressing the attached file to BC5, and while I can see its thumbnail in the GUI, the info pane fails to show the file dimensions and the CLI fails with "Error: loading source image". I suspect this is because the source image is using 16-bits per component.

![Bricks059_1K_NormalDX](https://user-images.githubusercontent.com/1711646/144452514-32e88886-5195-499c-bd3c-18af1973d2b7.png)

**Comment by NPCompress** [comment]
@sherief Processing for 16-bit PNG files has been added in our latest release
