### ISSUE TITLE
all the unwanted info in the filename

### ISSUE THREAD

**Issue by y2keeth** [GPUOpen-Tools/compressonator#195]
I am sure most people game wise need the dds to have the exact same name as the source texture  unless I just have not found the option to turn that off

**Comment by denislevesqueAMD** [comment]
@y2keeth That's a good point! It isn't currently an option, but we will be sure to add it to the next release.

**Comment by y2keeth** [comment]
good deal

**Comment by NPCompress** [comment]
@y2keeth  This option has been provided in our latest release. By default the destination names will not be changed unless a duplicate target name is found.
To restore the format that has renaming for all files enable -UseMangledFileNames in CLI or use the GUI "Applications Setting" window to enable it.

**Comment by y2keeth** [comment]
great
