### ISSUE TITLE
Incorrect ETC processing

### ISSUE THREAD

**Issue by lexaknyazev** [GPUOpen-Tools/compressonator#199]
The following ETC1 RGB data represents a solid yellow 4x4 block.
```
F8 F8 00 02 00 00 00 00
```

The Compressonator 4.2.5185 decodes it as cyan, i.e., it erroneously swaps red and blue channels. The encoder makes the same error.

**Comment by NavNTCMP** [comment]
@lexaknyazev  Issue addressed in v4.5 release
