### ISSUE TITLE
SDK example does not compile

### ISSUE THREAD

**Issue by RobDangerous** [GPUOpen-Tools/Compressonator#20]
Because of missing headers. Compressonator_Test.cpp includes Compressonator.h which does not exist in the SDK. There is only Compress.h which itself tries to pull in lots of headers which are not included in the SDK.

**Comment by NPCompress** [comment]
Looks like the installer is missing two include files. 

Here are the files: (Common.h and Compressonator.h)

[Include.zip](https://github.com/GPUOpen-Tools/Compressonator/files/687493/Include.zip)

Please unzip and copy them to the SDK include folder.

You can also find them in the Git Source folder "Headers"
A patch for the installer will be provided. ASAP.

**Comment by RobDangerous** [comment]
Those include more headers which are not included (starting with Codec.h). Just throwing in everything from the repo is also not sufficient because Compressonator uses a rather impressive list of include dirs.

**Comment by NPCompress** [comment]
I ran a dependancy graph on the sample project, Not sure why codec.h is pulled into the source build.

![image](https://cloud.githubusercontent.com/assets/18406717/21686163/68ed2db6-d332-11e6-9e69-9f99ba15bb2e.png)

We will investigate the issue further.

**Comment by RobDangerous** [comment]
Happens here: https://github.com/GPUOpen-Tools/Compressonator/blob/master/Compressonator/Header/Compress.h#L31

**Comment by NPCompress** [comment]
Are you building from the sample.sln

**Comment by RobDangerous** [comment]
No, that one was my fault, apparently I changed an include while trying to get it to compile.

**Comment by NPCompress** [comment]
Try using only Compressonator.h in the test sample. (which only pulls in Common.h)

**Comment by NPCompress** [comment]
The project sample uses relative path for the headers. It can also use a system environment variable "compressonator_root" to set the header path. The installer should have set it be default to you installed folder.

**Comment by RobDangerous** [comment]
Right, fresh copy plus the two includes and everything compiles. Sorry and thanks.

**Comment by NPCompress** [comment]
Thanks for bringing the issue up.
Please feel free to suggest any improvements or new ideas you would like to see in the tool kit
