### ISSUE TITLE
Crash during creating mip maps

### ISSUE THREAD

**Issue by Andreyogld3d** [GPUOpen-Tools/compressonator#202]
Hi ! I use last version of AMD Compressonator.

![image](https://user-images.githubusercontent.com/8597425/154668594-55571d10-5086-4352-bc52-bd1ef21b81ff.png)
During creation mim maps I have got crash.

![image](https://user-images.githubusercontent.com/8597425/154669358-880c48bc-3e00-4919-8943-221b109bdd22.png)

![image](https://user-images.githubusercontent.com/8597425/154668540-88d38986-884a-49b7-919f-09be4034b351.png)
I have attached image 

[particle_smoke.dds.zip](https://github.com/GPUOpen-Tools/compressonator/files/8096511/particle_smoke.dds.zip)

**Comment by Andreyogld3d** [comment]
@ymmikhail , Hi
Also Compressonator crashes during creating mip levels for DDS texture with format A1RGB5
[vishka.zip](https://github.com/GPUOpen-Tools/compressonator/files/8172975/vishka.zip)

**Comment by GITNE** [comment]
Depending on the texture compression algorithm you are encoding to your lowest mip level must not be smaller than the algorithm’s block size, often 4x4. However, the UI should account for that depending on the selected texture compression algorithm and make it impossible for the user to go below that defined threshold.

**Comment by denislevesqueAMD** [comment]
@Andreyogld3d These crashes will be fixed in the next release.

**Comment by Andreyogld3d** [comment]
Crash fixed, Thanks,
Will be implemented reading and converting DDS textures A1R5G5B5 ? see https://github.com/GPUOpen-Tools/compressonator/files/8172975/vishka.zip
