### ISSUE TITLE
CompressonatorV4.2 run very slowly

### ISSUE THREAD

**Issue by xiazhibin** [GPUOpen-Tools/compressonator#203]
Test in Ubuntu 20.04

I upgrade Compressonator V3.2 to V4.2  which from release page, test with a 1024*1024 png in `./compressonatorcli -fd ASTC test.png -Quality 1 -miplevels 11 test.ktx`.

V4.2 run very very very slowly but V3.2 is pretty fast.

I try V4.1 also. And I find that V3.2 faster than V4.1 faster than V4.2.
Is there something wrong?

**Comment by ymmikhail** [comment]
Hi @xiazhibin, thanks for your report. We're looking into this issue

**Comment by xiazhibin** [comment]
Thanks for your reply!!
