### ISSUE TITLE
batch .tga to mipmap .DDS

### ISSUE THREAD

**Issue by ryutoshirazen** [GPUOpen-Tools/Compressonator#21]
I'm trying to batch convert about 900 or so images in batches of about 101 with mipmaps.
This conversion works fine in the compressonator gui. (Edit: Version 2.4.3214.0)
example:
ProgressBarBattery_SC_000.tga
mipmap level set to 5

Converting to DXT5
Quality set to 0.5000
Adaptive is unchecked

Name: ProgressBarBattery_SC_000 | Dropdown is on DDS

Source is D:/ Drive | Destination is D:/ Drive  In an alternate Folder
Settings saved | Process | ===Compress: 1 succeeded, 0 failed===
I check the file and.... Perfection

Then I export the settings to batch file. I made multiple batch files for image sets in groups of 101. Double checked my batch files and saved. Placed the bat files in the compressonator install folder(C:/Program Files/Compressonator and ran first batch file. Bat file ran and closed so I checked my processed file folder and... its empty?

Okay so need a small test to see whats going on. Back to original test image.
I delete the test result from the gui from earlier. Open the original batch and it lines up with what is shown in Output window of gui. I run the bat file and.... processed folder is empty. HUH?
so I add a cmd command I remembered of the top of my head to the test bat file. 
pause
Ran the bat file again and yay it paused. This is what I see.

CompressonatorCLI.exe "D:/...(EDITED).../ProgressBarBattery_SC_000.tga" "D:/...(EDITED).../ProgressBarBattery_SC_000.DDS"  -fd DXT5  -miplevels 5  -Quality 0.5000
Source Texture size = 1048576 Bytes, width = 512 px  height = 512 px
Destination Texture size = 262144 Bytes    Resulting compression ratio = 4.00:1
Compression progress = 94Source Texture size = 262144 Bytes, width
 = 256 px  height = 256 px
Destination Texture size = 65536 Bytes    Resulting compression ratio = 4.00:1
Compression progress = 88   MipLevel =  2Source Texture size = 65536 Bytes, width
 = 128 px  height = 128 px
Destination Texture size = 16384 Bytes    Resulting compression ratio = 4.00:1
Compression progress = 75   MipLevel =  3Source Texture size = 16384 Bytes, width
 = 64 px  height = 64 px
Destination Texture size = 4096 Bytes    Resulting compression ratio = 4.00:1
Compression progress = 50   MipLevel =  4Source Texture size = 4096 Bytes, width
 = 32 px  height = 32 px
Destination Texture size = 1024 Bytes    Resulting compression ratio = 4.00:1
Compression progress = 0     MipLevel =  5Source Texture size = 1024 Bytes, width
 = 16 px  height = 16 px
Destination Texture size = 256 Bytes    Resulting compression ratio = 4.00:1
Compression progress = 100 MipLevel =  6Error: saving image or format is unsupp
orted

Is it a bug in the batch converter code or
Do I Need to convert from tga to something else then to .dds?
If I need to double convert then what should I convert to before moving to .dds conversion?

**Edit**
Okay... ran another test. Moved the target file from D drive to the compressonator image folder.
Source C:\Program Files\Compressonator\images\ProgressBarBattery_SC
Desti.... C:\Program Files\Compressonator\images\ProgressBarBattery_SC2

Converted properly from bat. I can work with this. Seems to have issue with heavily nested folder paths or folder paths with long names.

C:/Program Files/Compressonator/images/ProgressBarBattery_SC/ProgressBarBattery_SC_000.tga
Worked
D:/ProgressBarBattery_SC/ProgressBarBattery_SC_000.tga
Worked
D:/Modding Files/ProgressBarBattery_SC/ProgressBarBattery_SC_000.tga
Worked
D:/Modding Files/Space Engineers/ProgressBarBattery_SC/ProgressBarBattery_SC_000.tga
Worked
D:/Modding Files/Space Engineers/Test Mod Textures/ProgressBarBattery_SC/ProgressBarBattery_SC_000.tga
Failure

I was working from deeper folders than that. I do love my folders... ugh. well i can work with this by moving my files then doing batch convert then moving them to where I want them. Still easier than the alternative.

Yes I have admin rights. I'm the only one that uses this personally built pc. Even if I didn't, I know how to give myself permissions. I didn't do the admin cmd bit i've just been running the bat directly by double clicking on it.

But seriously check that out and see if you could do something about that path length issue. would be greatly appreciated. Keep up the great work. XD Thanks

**Comment by xooiamd** [comment]
hi @ryutoshirazen , my guess is you are not the admin, so can't make any change (write access) to the C:/Program Files/  path in your system, but i am not sure. Can you try open your cmd window by "run as administrator" and navigate to the compressonator install path (C:/Program Files/Compressonator) then run your batch file through the cmd window? 
Thanks

**Comment by NPCompress** [comment]
Hi 
I tried to duplicate your issue and was unsuccessful in reproducing!

Here are the steps I used.

Created a batch file NewProject.bat with the content as shown below using the GUI

CompressonatorCLI.exe  "E:/Test/ruby.tga"   "E:/Test/ruby_TGA_DXT5_1.DDS"   -fd DXT5  -miplevels 5  -Quality 0.5000 

64 bit Compressonator is installed by default on C:\Program Files\Compressonator, Going into command prompt with administrator permission, I copied the batch file to that folder and ran it.

Maybe its an issue with admin settings!

No need to convert TGA file, compressing directly to DDS is ok.

**Comment by ryutoshirazen** [comment]
Main post edited if you didn't see.

Funny enough tried running it from admin cmd for shits and giggles at path
D:/Modding Files/Space Engineers/Test Mod Textures/ProgressBarBattery_SC/ProgressBarBattery_SC_000.tga
and where it failed before it succeeded.

though implementing batch processing into the GUI would be much nicer.
something as simple adding a bunch of files then using just a master destination with master settings to be applied to all files in the gui list. Or using a master destination and settings that could accompany individual settings or be overridden by individual settings.

I like batch processing guis. I use gimp and it has through plugins batch layer processing and batch file processing with guis.

anyways thanks for your help. since i found a way to make it work without having to go into the admin cmd this issue can be closed.
