### ISSUE TITLE
Compressonator batch error

### ISSUE THREAD

**Issue by ketxxx** [GPUOpen-Tools/compressonator#211]
I'm new to compressonator so this could be something extremely simple, but in short I have a bunch of BC7,4, etc files I want to convert to BC3, however when I load all the textures in compressonator and hit the button to convert them I get this error; compressed source and compressed destination selection is not supported.

What am I doing wrong here? Nothing I've tried seems to work and google isn't offering any answers.

EDIT: Wait.. do I REALLY have to save the images as something like ARGB_32F then go through the whole process again saving them to BC3?

**Comment by NPCompress** [comment]
@ketxxx  The current code is setup to work the way you described. For the next release we will enable transcoding from one BCn format to another BCn format.

**Comment by ketxxx** [comment]
@NPCompress Thanks for the clarification, I realised I was doing it right when I somehow didn't see the "User Guide" link staring me in the face in Compressonator. Since using the application though I have noticed what seems like some rather strange behaviour that might be bugs so I'll list them bullet style;

1. When converting BC7 to ARGB_8888 Compressonator will randomly crash with no error the application will just close down during the conversion process. I'm just theorizing here but if not a bug per-se maybe some kind of conflict with Windows randomised memory allocation?

2. Again this might not be a bug but BC7 format doesn't generate legible thumbnails they are all a fuzzy garble so as you can imagine this slows my workflow down considerably (I'm working with literally thousands of images). I've tried several different thumbnail plugins for Windows including Sagethumbs v2.0.0.23 and Mysticthumbs v1.98. 

3. Lastly, a suggestion. Having all of the converted images renamed with what format they are converted to is a massive inconvenience, having to renamed hundreds of images per folder is not fun, why not leave the filename alone and instead of having a generic "results" folder have the folder name represent the converted images format. Eg; Results > ARGB_8888, etc.

**Comment by NPCompress** [comment]
@ketxxx  We have now featured a option to turn off file renaming and improved batch processing. This will also be available in our next release.

**Comment by ketxxx** [comment]
@NPCompress that's awesome to know I'll look forward to being able to test those improvements out in the next release! Any ETA on when the release might be ready?

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
