### ISSUE TITLE
BC6H encoder is non-deterministic due to reading uninitialized memory

### ISSUE THREAD

**Issue by jspohr** [GPUOpen-Tools/compressonator#212]
I noticed that back-to-back encodes with BC6H on CPU were producing different results.
I'm using CMP_Core with both MSC (Win64) and Clang (Mac), both platfoms show this bug.

I debugged CompressBlockBC6_Internal and noticed that the array `shape_indicesB` in `FindBestPattern` isn't initialized:
https://github.com/GPUOpen-Tools/compressonator/blob/58a866176ef0db6177881c2040144632841c8233/cmp_core/shaders/bc6_encode_kernel.cpp#L2202

This might not always be the case, depending on the target language and platform, but I think in both C++ and OpenCL you can't rely on the local array being initialized, so at least in my use case it will contain undefined values.
This array is being read in [`optQuantAnD_d`](https://github.com/GPUOpen-Tools/compressonator/blob/58a866176ef0db6177881c2040144632841c8233/cmp_core/shaders/bc6_encode_kernel.cpp#L994) and it produces different results depending on the undefined values in the array.

Now, there are two things about `optQuantAnD_d` I don't understand, so I didn't create a PR (even though initializing the array to 0 fixed the non-deterministic behavior), and I want to get a better understanding first.

1. This loop is obviously never entered:
https://github.com/GPUOpen-Tools/compressonator/blob/58a866176ef0db6177881c2040144632841c8233/cmp_core/shaders/bc6_encode_kernel.cpp#L1035-L1044
I think it should say `for (i = 0; i < MAX_ENTRIES; i++)` instead.
This _would_ initialize the `index` array, but the function returns after the loop anyway.

3. There's another local array called `index_` (note the underscore), and there might be a bug there: https://github.com/GPUOpen-Tools/compressonator/blob/58a866176ef0db6177881c2040144632841c8233/cmp_core/shaders/bc6_encode_kernel.cpp#L1116-L1120
The last statement is redundant, but it might be helper to put a breakpoint on, I'm not sure.

As I mentioned, for now I have fixed the non-determinism by changing
```
    CGU_INT   shape_indicesB[2][MAX_SUBSETS][MAX_SUBSET_SIZE];
```
into
```
    CGU_INT   shape_indicesB[2][MAX_SUBSETS][MAX_SUBSET_SIZE] = {};
```
However, I'm not sure if this is the correct fix, or if this might break any of the other target's builds.

Thanks!

**Comment by denislevesqueAMD** [comment]
Thanks for the detailed report! We will be looking into this.
