### ISSUE TITLE
CLI: CompressonatorCLI -fd BC7 .\images .\results -logfile a.txt

### ISSUE THREAD

**Issue by wjd000** [GPUOpen-Tools/compressonator#213]
Processes all image file with BC7 Compression into results folder.
But in fact, all the generated files are in the C drive.
Why?

The following shows the information in a.txt：
CompressonatorCLI Performance Log v1.3

Negative values are errors in measurement Sets ErrCode > 0 else 0 for none
For images with no errors MSE= 0 PSNR=255 and SSIM= 1.0
Transcoded images         MSE= 0 PSNR=255 and SSIM=-2.0
No image data generated   MSE=-1 PSNR= -1 and SSIM=-1.0 with ErrCode set

Source       : C:/Compressonator_4.2.5185/bin/CLI/images\balls.exr, Height 784, Width 1000, Linear size 6.272 MB
Destination  : /balls_exr_BC7.dds
Processed to : BC7        with  1 iteration(s) in 0.465 seconds
Using        : CPU
Quality      : 0.05
KPerf(ms)    : 0.000
MTx/s        : 0.000
MSE          : 1.9447
PSNR         : 45.24
SSIM         : 0.9905
Total time(s): 0.761
Source       : C:/Compressonator_4.2.5185/bin/CLI/images\ruby.bmp, Height 416, Width 576, Linear size 0.958 MB
Destination  : /ruby_bmp_BC7.dds
Processed to : BC7        with  1 iteration(s) in 0.077 seconds
Using        : CPU
Quality      : 0.05
KPerf(ms)    : 0.000
MTx/s        : 0.000
MSE          : 0.7796
PSNR         : 49.21
SSIM         : 0.9978
Total time(s): 0.078
Source       : C:/Compressonator_4.2.5185/bin/CLI/images\ruby.dds, Height 416, Width 576, Linear size 0.958 MB
Destination  : /ruby_dds_BC7.dds
Processed to : BC7        with  1 iteration(s) in 0.084 seconds
Using        : CPU
Quality      : 0.05
KPerf(ms)    : 0.000
MTx/s        : 0.000
MSE          : 0.7796
PSNR         : 49.21
SSIM         : 0.9978
Total time(s): 0.085
Source       : C:/Compressonator_4.2.5185/bin/CLI/images\ruby.png, Height 416, Width 576, Linear size 0.958 MB
Destination  : /ruby_png_BC7.dds
Processed to : BC7        with  1 iteration(s) in 0.082 seconds
Using        : CPU
Quality      : 0.05
KPerf(ms)    : 0.000
MTx/s        : 0.000
MSE          : 0.7796
PSNR         : 49.21
SSIM         : 0.9978
Total time(s): 0.083
Source       : C:/Compressonator_4.2.5185/bin/CLI/images\ruby.tga, Height 416, Width 576, Linear size 0.958 MB
Destination  : /ruby_tga_BC7.dds
Processed to : BC7        with  1 iteration(s) in 0.095 seconds
Using        : CPU
Quality      : 0.05
KPerf(ms)    : 0.000
MTx/s        : 0.000
MSE          : 0.7796
PSNR         : 49.21
SSIM         : 0.9978
Total time(s): 0.096
Source       : C:/Compressonator_4.2.5185/bin/CLI/images\ruby.tif, Height 416, Width 576, Linear size 0.958 MB
Destination  : /ruby_tif_BC7.dds
Processed to : BC7        with  1 iteration(s) in 0.083 seconds
Using        : CPU
Quality      : 0.05
KPerf(ms)    : 0.000
MTx/s        : 0.000
MSE          : 0.7796
PSNR         : 49.21
SSIM         : 0.9978
Total time(s): 0.084
Source       : C:/Compressonator_4.2.5185/bin/CLI/images\ruby_alpha.tga, Height 600, Width 800, Linear size 1.920 MB
Destination  : /ruby_alpha_tga_BC7.dds
Processed to : BC7        with  1 iteration(s) in 0.085 seconds
Using        : CPU
Quality      : 0.05
KPerf(ms)    : 0.000
MTx/s        : 0.000
MSE          : 0.7101
PSNR         : 49.62
SSIM         : 0.9986
Total time(s): 0.086

**Comment by wjd000** [comment]
I try another version 3.1.4064,it's ok. May be there are some bugs in version 4.2.5185?

**Comment by denislevesqueAMD** [comment]
Thanks for the report @wjd000, we will be looking into this issue.
