### ISSUE TITLE
silent option doesn't disable message output

### ISSUE THREAD

**Issue by helviett** [GPUOpen-Tools/compressonator#218]
`compressonatorcli.exe -fd ETC2_RGBA -nomipmap -noprogress -silent .\Bg.png .\Bg.ktx`

Gives output:

```

Source Texture size = 524288 Bytes, width = 256 px  height = 512 px
Destination Texture size = 131072 Bytes   Resulting compression ratio = 4.00:1
```

But should output nothing.

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
