### ISSUE TITLE
Get image properties using CLI

### ISSUE THREAD

**Issue by BigheadSMZ** [GPUOpen-Tools/Compressonator#22]
I've read all documentation I could possibly get my hands on, but I could not find if it's possible to just simply read an image using the command line version and echo the properties of the image. For example, when loading an image into the GUI, a "Properties" window has the following information for a DDS file:

Name/Full Path/Full Size/Image Size/Width/Height/Mip Levels/Format

This simple feature would be very useful. When running a task on multiple images that we may not know the specifics to, knowing this information beforehand could allow assigning tasks to different image types within a script.

**Comment by xooiamd** [comment]
Hi, please pull the latest commit [30f12b2](https://github.com/GPUOpen-Tools/Compressonator/commit/30f12b2b565215039bafc0ed692390be61bd8ba8) and buildCLI to get the "read an image properties" using the command line app.  You can get the image properties by running the command "compressonatorcli -imageprops <image file>" . Let us know if there is further issues. Thanks!

**Comment by BigheadSMZ** [comment]
Thank you this is exactly what I was looking for!
