### ISSUE TITLE
Potential stack corruption in CMP_ProcessTexture

### ISSUE THREAD

**Issue by sndels** [GPUOpen-Tools/compressonator#221]
Hey, it looks like [CMP_ProcessTexture](https://github.com/GPUOpen-Tools/compressonator/blob/bab59d4330e64612a1bb0c18dce0f70b48fef395/cmp_framework/compute_base.cpp#L715) leads to stack corruption if calls to it happen from non-uniform call stacks.

When the function is called for the first time, with the global plugin uninitialized, a call [CMP_CreateComputeLibrary](https://github.com/GPUOpen-Tools/compressonator/blob/bab59d4330e64612a1bb0c18dce0f70b48fef395/cmp_framework/compute_base.cpp#L817)  ends up initializing the global (e.g. [CCPU_HPC](https://github.com/GPUOpen-Tools/compressonator/blob/bab59d4330e64612a1bb0c18dce0f70b48fef395/applications/_plugins/ccmp_encode/hpc/compute_cpu_hpc.cpp#L269)). This stores a pointer to the `KernelOptions` that was passed by value into `CMP_ProcessTexture`. This is fine as the stack variable will live for the duration of that call.

However, [CMP_DestroyComputeLibrary](https://github.com/GPUOpen-Tools/compressonator/blob/bab59d4330e64612a1bb0c18dce0f70b48fef395/cmp_framework/compute_base.cpp#L854) is only called with `forceclose = false`. This will leave the plugin hanging around and any further calls will try to use the pointer to `KernelOptions` as it was on the previous stack. Chaos ensues if `CMP_ProcessTexture` is called again with a call stack that looks different from the first one.

This seems to be easily fixed by calling `CMP_DestroyComputeLibrary(true)` in potentially non-uniform callsites, but I'm wondering if there should be flag in the API to handle that automagically, making this footgun more obvious 😅 Maybe even lift the creation and destruction of the plugins entirely out of `CMP_ProcessTexture` and give the responsibility to the caller, if it's common to reuse plugins with the same options.

**Comment by NPCompress** [comment]
@sndels Nice find on this issue, will look into additional feature options to handle this

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
