### ISSUE TITLE
YCoCg scaled DXT5

### ISSUE THREAD

**Issue by y2keeth** [GPUOpen-Tools/compressonator#230]
where is that in the menu gui?

**Comment by NPCompress** [comment]
@y2keeth  The GUI does not have any options for YCoCg image compression into DXT5. It will use these color channel options:
        DXT5,
        DXT5_xGBR,
        DXT5_RxBG,
        DXT5_RBxG,
        DXT5_xRBG,
        DXT5_RGxB,
        DXT5_xGxR,
Which can be set in Add Destination Setting options format.

![image](https://user-images.githubusercontent.com/18406717/218324987-069cae55-99e7-4b67-839b-56cb48bf529d.png)

**Comment by y2keeth** [comment]
so there is no option

**Comment by y2keeth** [comment]
trying to get the highest quality possible

**Comment by y2keeth** [comment]
is it possible to do RXGB uncompressed?
