### ISSUE TITLE
v4.3.206 build failure due to external deps specification

### ISSUE THREAD

**Issue by seragh** [GPUOpen-Tools/compressonator#231]
Glad to see a new release

just that configuring with -DOPTION_ENABLE_ALL_APPS=OFF -DLIB_BUILD_FRAMEWORK_SDK=ON results in failure.

glm and glfw obviously can't be found in ${PROJECT_SOURCE_DIR}/../common

both could be found on the system with find_package if needed but don't seem to be required for core / compressonator_sdk / framework_sdk in the first place.

**Comment by NPCompress** [comment]
@seragh  Thanks for this notification, we will look into this and provide an update in main branch
