### ISSUE TITLE
Why is ASTC Support removed?

### ISSUE THREAD

**Issue by Docteh** [GPUOpen-Tools/compressonator#238]
I'm noticing that in the releases page for [V4.3.206](https://github.com/GPUOpen-Tools/compressonator/releases/tag/V4.3.206) in the features list there is mention of removal of ASTC support.

I tried looking in the commit history for a reason, and searched the issue tracker but I'm not seeing any commentary on it. I can easily use the older versions, so I'm not too worried about the lack of ASTC support. 

But I would like to know the reason why.

----
My use case, mainly for understanding

VRChat currently uses Unity 2019.4.31f1, and for ASTC textures the unity editor takes a decent amount of time to encode the texture, and doesn't seem to give me an option to extract the processed textures. 

* [ARM-software/astc-encoder](https://github.com/ARM-software/astc-encoder) works but they've opted to not support mip levels https://github.com/ARM-software/astc-encoder/issues/145 issue suggests `toktx`
* [KhronosGroup/KTX-Software](https://github.com/KhronosGroup/KTX-Software), home of `toktx`. I fumbled around with this and couldn't get a file that the older Unity would accept, I believe it was only giving ktx2 format files
* Compressonator, I have to flip the input file horizontally as the compression flips it, but otherwise I  can get an ASTC texture that can be dropped directly into unity. Compresses slower than Unity, but being able to take the compressed result and email/put into other project is compelling

**Comment by cal3d** [comment]
It was removed primarily to ease future maintenance. ASTC isn't supported on desktop PC or console platforms which are the primary audience for compressonator.

**Comment by mixtur** [comment]
The Readme still mentions ASTC. Is this correct?

Also Nintendo Switch and older Intel GPUs support ASTC, so your PC-console argument is not exactly valid.

I do WebGL and I would really like a tool that would convert to all the formats webgl supports. One other candidate tool would be PvrTexToolCLI but they don't support BC7.
