### ISSUE TITLE
CCodecBuffer_RGB888 sizeof() bug

### ISSUE THREAD

**Issue by carlschissler** [GPUOpen-Tools/compressonator#241]
There is a bug in the implementation of CCodecBuffer_RGB888::WriteBlockRGBA(), as well as CCodecBuffer_RGB888S::WriteBlockRGBA() (these are the only places I looked, but it might be elsewhere). Scanning the rest of the file, I see lots of sizeof(nChannelCount) everywhere, which is probably in error as well. All buffer types need a thorough checking for this bug.

The line that calculates the offset to write in the destination image reads:
CMP_BYTE* pDestData = (CMP_BYTE*) (GetData() + ((y + j) * m_dwPitch) + (x * sizeof(nChannelCount)));

It should be: (note lack of sizeof())
CMP_BYTE* pDestData = (CMP_BYTE*) (GetData() + ((y + j) * m_dwPitch) + (x * nChannelCount));

This causes RGB images (e.g. DXT1) to be scrambled upon decoding to uncompressed RGB, because the offset is calculated with sizeof(), which always evaluates to 4.

Has no one actually tested this code?

**Comment by denislevesqueAMD** [comment]
@carlschissler Thanks for all the issue reports!

We are currently looking into this issue, as well as the others you have reported recently, and will be trying to fix as many as we can for the next release.

Rest assured that we are taking your comments to heart!

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
