### ISSUE TITLE
BC7 repeated Quant_Init() is very slow

### ISSUE THREAD

**Issue by carlschissler** [GPUOpen-Tools/compressonator#242]
When doing any BC7 texture conversion using the CMP_ConvertTexture() API, there is a very slow overhead in every function call that in most cases takes longer than decoding the image itself.

For example, here is how long it takes to decompress BC7 for different mips of a 1024px image on a desktop PC: (times in seconds)
< 1024, 1024, 1 > 0.06778
< 512, 512, 1 > 0.037129
< 256, 256, 1 > 0.028415
< 128, 128, 1 > 0.027362
< 64, 64, 1 > 0.026131
< 32, 32, 1 > 0.026182
< 16, 16, 1 > 0.024796
< 8, 8, 1 > 0.024865
< 4, 4, 1 > 0.024869
< 2, 2, 1 > 0.024796
< 1, 1, 1 > 0.037259

As you can, see even a 1x1 pixel texture has an overhead of about 25 milliseconds. This really adds up for the tiny mips. After profiling the code, I see that most of the time is spent in the Quant_Init() function (traceBuilder() to be specific), and only a minority of the time (<20%) is spent actually doing useful work.

The culprit is that Quant_Init() is called within CMP_ConvertTexture(), followed always be Quant_DeInit(). Despite the reference counting in Quant_Init(), this common usage pattern results in the BC7 trace builder to always be run, and then destroyed, resulting in the very slow behavior observed above.

I can think of a few possible solutions:
1. Never clean up the data initialized by Quant_Init(). Once it's created, it stays valid in memory until the process is destroyed. This would mean that Quant_DeInit() becomes a no-op. I did this change in my local code and it works great.
2. Change the whole API so that I can allocate a "TextureCompressor" object that can be reused for multiple calls to CMP_ConvertTexture(). TextureCompressor can store the tables needed for BC7 and clean them up when the user is finished. This also avoids other issues with globals and thread safety and is a much better design than the current API.

With proposed change #1, I now get the following performance in the benchmark:
< 1024, 1024, 1 > 0.043163
< 512, 512, 1 > 0.011473
< 256, 256, 1 > 0.002745
< 128, 128, 1 > 0.000681
< 64, 64, 1 > 0.000229
< 32, 32, 1 > 0.00006
< 16, 16, 1 > 0.000014
< 8, 8, 1 > 0.000006
< 4, 4, 1 > 0.000004
< 2, 2, 1 > 0.000004
< 1, 1, 1 > 0.000004
Much better!

**Comment by NPCompress** [comment]
The issue has been resolved in current release v4.4
