### ISSUE TITLE
Can't disable multithreading for ASTC compression

### ISSUE THREAD

**Issue by AlexanderN** [GPUOpen-Tools/Compressonator#25]
Hi

We currently compress with the multithreading disabled option ("bDisableMultiThreading") and encountered an issue. When we started compressing ASTC textures, we occationally ran into the following error message, coming from ASTC_Encode_Kernel:
"Unable to find an encoding within the specified error limits. Please revise the error limit values and try again."

I tried debugging it and it seems like setting the "bDisableMultiThreading" option to false did not prevent the ASTC encoding from running multithreaded.

In Compress.cpp around line 460 where there is a switch statement "switch(destType)", I saw that for CT_BC7, NumThreads were being set to either the "dwnumThreads" option or 1 depending on the "bDisableMultiThreading" option, but for ASTC, NumThreads were never set, causing it to used the default (8).

**Comment by NPCompress** [comment]
Hi AlexanderN,

Are you using the prebuilt command line tool or are you building from source?

A fix is been worked on to allow disabling of ASTC multithreading from the command line and source updates will be posted soon.

**Comment by NPCompress** [comment]
After further investigation, MultiThreading for ASTC can be turned off in the existing code by applying the command line   -NumThreads 1

Please give this a try for your setup.  

As for the message "Unable to find an encoding within the specified error limits. Please revise the error limit values and try again."
Have you tried adjusting the command line quality setting -Quality 0.05 to some other value in the range of 0.0 to 1.0

**Comment by AlexanderN** [comment]
Ah, great:)

I'm building from source and referencing the dll. I call with these options: 
bDisableMultiThreading = true
dwnumThreads = 1
fquality = 1

I'll check if I can figure out if it corresponds to the command line option for NumThreads and Quality and validate my input. I can try and see if I can get a repro using the command line tool.

**Comment by AlexanderN** [comment]
When entering CompressTexture in Compress.cpp, the fquality, bDisableMultiThreading and dwnumThreads all seem to be 1. I tried running with fquality set to "0", "0.5" and "1", but I got the same issue regardless. It's not very urgent, so I could just wait for the fix you mentioned though. 

I think the error message is related to running multithreaded ("Unable to find an encoding within the specified error limits. Please revise the error limit values and try again."). I don't get it if I just change the NumThreads manually in the code in order to make it run with multithreading disabled (early in Compress.cpp, CompressTexture).

**Comment by NPCompress** [comment]
Thanks for the information on your setup.
In the source code for Compress.cpp after line 473 in the switch statement for case CT_ASTC: you can insert
                pCodec->SetParameter("NumThreads", (CMP_DWORD)pOptions->dwnumThreads);
This will fix the source program option setting of NumThreads to turn off MultiThreading for ASTC.

We will continue to investigate why the issue is there for MultiTheaded and not for single theaded.

**Comment by AlexanderN** [comment]
Thank you, I'll do so :)
