### ISSUE TITLE
error

### ISSUE THREAD

**Issue by y2keeth** [GPUOpen-Tools/compressonator#251]
Processing: rl_lo_dold
compressonatorcli.exe  "E:/SteamLibrary/steamapps/common/Quake 4/q4base/models/weapons/rocketlauncher/rl_lo_dold.dds" "E:/SteamLibrary/steamapps/common/Quake 4/q4base/models/weapons/rocketlauncher/results/rl_lo_dold.DDS"  -fd DXT5_RxBG  -Quality 1.0000  -NumThreads 16 
Transcoding Error: Compressed source and compressed destination selection is not supported
Processed in 0.02 seconds
====== Compress: 0 succeeded, 1 failed ======
Processing: rl_lo_dold
compressonatorcli.exe  "E:/SteamLibrary/steamapps/common/Quake 4/q4base/models/weapons/rocketlauncher/rl_lo_dold.dds" "E:/SteamLibrary/steamapps/common/Quake 4/q4base/models/weapons/rocketlauncher/results/rl_lo_dold.DDS"  -fd DXT5_RxBG  -Quality 1.0000  -NumThreads 16 
Transcoding Error: Compressed source and compressed destination selection is not supported
Processed in 0.00663 seconds
====== Compress: 0 succeeded, 1 failed ======

**Comment by y2keeth** [comment]
[](https://pasteboard.co/UXZVZYhC4KhT.png)

**Comment by denislevesqueAMD** [comment]
Hi @y2keeth, it looks like you're trying to convert a compressed image directly to a different compressed format. This isn't a feature that is broadly supported in Compressonator at the moment.

It is possible to convert textures between BCn formats directly as of version 4.3 (like BC3 -> BC7 for example), but not for other compressed formats.

**Comment by y2keeth** [comment]
ok 
 any info about RXGB dtx5 uncompressed?

**Comment by y2keeth** [comment]
> ok
> any info about RXGB dtx5 uncompressed?

**Comment by denislevesqueAMD** [comment]
@y2keeth The DXT5 RxGB format can be converted to any uncompressed format like RGBA8888 using Compressonator. The results might look a bit weird since the DXT5 RxGB format is a swizzled format where the blue channel and alpha channel are swapped.

**Comment by y2keeth** [comment]
what is the x channel in RXGB?

**Comment by denislevesqueAMD** [comment]
@y2keeth The "X" in RXGB is a stand-in for the alpha channel. As for why it's an 'X' instead of an 'A', I'm not totally sure. My guess is that for this format the actual contents of the alpha channel were typically not that important.

**Comment by y2keeth** [comment]
ok thanks

**Comment by y2keeth** [comment]
RXGB with the argb_8888 compression is that possible?
