### ISSUE TITLE
Some declarations in compressonator.h are not defined in Compressonator_xx.lib

### ISSUE THREAD

**Issue by bekorn** [GPUOpen-Tools/compressonator#257]
Hello,

I downloaded [CompressonatorSDK_x64_4.3.206.exe](https://github.com/GPUOpen-Tools/compressonator/releases/tag/V4.3.206) and setup a project with include/compressonator.h and lib/VS2019/x64/Compressonator_MD.lib to run the examples/sdk_example1/SDK_example.cpp. Everything worked and I compressed ruby.dds into ruby.dds but BC7 👌.

I tried to follow the comment in the example 
https://github.com/GPUOpen-Tools/compressonator/blob/38081a04f0e42c9f57206a5374b44ba81eca907d/examples/sdk_example1/sdk_example1.cpp#L37-L38

Added this line to test if it will build `auto * func_ptr = CMP_LoadTexture`

It failed with the error `main.cpp.obj : error LNK2019: unresolved external symbol CMP_LoadTexture referenced in function main`

Did a quick test and only the functions `CMP_Format2FourCC, CMP_IsCompressedFormat, CMP_IsFloatFormat` are defined in this block of declerations https://github.com/GPUOpen-Tools/compressonator/blob/38081a04f0e42c9f57206a5374b44ba81eca907d/cmp_compressonatorlib/compressonator.h#L982-L997

This seemed like an issue on your side, hence this report.

---

Additionally:
- Is there a utility in the SDK that can load various image formats besides dds (especially png/jpg/hdr)?
- How can I run CMP_ConvertTexture & CMP_ConvertMipTexture on the GPU? The SDK section of the documentation does not mention this.

**Comment by FilippoLeon** [comment]
Same issue with the missing symbols in the .lib.

**Comment by NavNTCMP** [comment]
@bekorn  Issue addressed in v4.5 release
