### ISSUE TITLE
CMP_ConvertTexture(...) is not thread-safe

### ISSUE THREAD

**Issue by zigguratvertigo** [GPUOpen-Tools/Compressonator#26]
_CMP_ConvertTexture(...)_,  as mentioned in the Example1 [here](https://github.com/GPUOpen-Tools/Compressonator/blob/master/Compressonator/Examples/Compressonator_Test.cpp) is not thread safe. If one calls the function in a multi-threaded fashion, crashes in the BlockEncoder.

As suggested by David Wilkinson @ AMD, one work around is to wrap the call with mutexes. I used a `std::lock_guard<std::mutex>`.

**Comment by repi** [comment]
I would like to highlight the importance of this. We manage parallelism ourselves outside of Compressonator by processing textures in parallel so currently all of our texture compression runs ~40 times slower (48 LP machine) when one has to serialize all the compression work to work on an individual face/mipmap for a single texture at a time. So this is a must fix

**Comment by NPCompress** [comment]
We are working on the issue and will provide an updated example sample and fix asap.

**Comment by NPCompress** [comment]
We have a working solution for BC7 today, that is been tested with a number of multithreaded samples. If you prefer we can submit or attach the changes; while we continue the testing for publication in the next release of the code

**Comment by zigguratvertigo** [comment]
Attaching the changes would be awesome. Thanks!! :)

**Comment by NPCompress** [comment]
[BC7Multuthread issue.zip](https://github.com/GPUOpen-Tools/Compressonator/files/1300027/BC7Multuthread.issue.zip)

The file changes are attached - The code may have issues and needs to run through qualification.
The Sample Example code has been updated : You can use example 2 to test the multithreading of BC7 The command line arguments should be repeated twice to test two concurrent image compressions

Assistance or changes in further code changes are welcome.

**Comment by NPCompress** [comment]
Some minor changes to Quant_Init() (Aviod using locks to keep code performance!)
[3dquant_vpc.zip](https://github.com/GPUOpen-Tools/Compressonator/files/1300474/3dquant_vpc.zip)

Continuing tests... Will post changes to repo when stable.

**Comment by NPCompress** [comment]
Notes: To avoid memory access issues in BC7 Codec when used in parallelism

Call CMP_InitializeBCLibrary() prior to using the BC7 Codecs when Multithreading CMP_ConvertTexture() calls and then clenup with CMP_ShutdownBCLibrary(); when done, this will guard the global memory variables used by the codec and improve performance for multiple calls to the BC7 codec classes.

**Comment by zigguratvertigo** [comment]
Sounds good. Will try your latest changes.

**Comment by NPCompress** [comment]
zigguratvertigo: Did you try the latest changes, Are there any issues that need our attention?

**Comment by zigguratvertigo** [comment]
Just got back from vacation. Will try those today.

**Comment by zigguratvertigo** [comment]
Tried it this was, issuing 28 compression requests at the same time, and unfortunately still crash:

`
CMP_InitializeBCLibrary();
cmp_status = CMP_ConvertTexture(&srcTexture, &dstTexture, &options, nullptr, 0, 0);
CMP_ShutdownBCLibrary();
`

Callstack:
- Quant_DeInit(void)
- CCodec_BC7::~CCodec_BC7(void)
- CCodec_BC7::vector deleting destructor'(unsigned int)
- CompressTexture(struct CMP_Texture const *,struct CMP_Texture *,struct CMP_CompressOptions const *,bool (*)(float,unsigned __int64,unsigned __int64),unsigned __int64,unsigned __int64,enum _CodecType)	
- CMP_ConvertTexture()

Same callstack if I remove the calls to initialize/shutdown the BC library.

Will investigate more but right now that's what I have.

**Comment by NPCompress** [comment]
Are you using 28 threaded calls wrapped within Init and Deinit 
like this example?

CMP_InitializeBCLibrary(); // Used only once

// Then CMP_ConvertTexture called by threads or serially like this
cmp_status = CMP_ConvertTexture(&srcTexture1, &dstTexture1, &options1, nullptr, 0, 0);
...
cmp_status = CMP_ConvertTexture(&srcTexture2, &dstTexture2, &options2, nullptr, 0, 0);
...
cmp_status = CMP_ConvertTexture(&srcTexture3, &dstTexture3, &options3, nullptr, 0, 0);
etc..

CMP_InitializeBCLibrary(); // Used only once

**Comment by zigguratvertigo** [comment]
Pretty much. Currently something in the form of:

uint32 threadCount = std::thread::hardware_concurrency();
uint32 useThreadCount = threadCount / 2; // run on 50% of the logical processors by default (skip hyperthreads essentially)
Concurrency::SchedulerPolicy policy(1, Concurrency::ContextPriority, THREAD_PRIORITY_LOWEST);
policy.SetConcurrencyLimits(1, useThreadCount);
Concurrency::CurrentScheduler::Create(policy);

CMP_InitializeBCLibrary();
Concurrency::parallel_for_each(...)
{
    CMP_ConvertTexture(...)
});
CMP_ShutdownBCLibrary();

![image](https://user-images.githubusercontent.com/1844966/30878049-fb0b869a-a2fb-11e7-9c53-cd4b4c3414f0.png)

**Comment by NPCompress** [comment]
This is very interesting. The examples test code does a similar test, diff code same idea... Will try using your code in the example to see if I can get the same error.

**Comment by NPCompress** [comment]
The Quant_Deinit should not be doing any deletes, until CMP_ShutdownBCLibrary(); 

Try this change in 3dquant_vpc.cpp

void Quant_Init(void)
{
    if (g_Quant_init > 0)
    {                        
        g_Quant_init++;   // add this
        return;
    }
    if (amd_codes[0][0])  return;
    for ( int ...) { ... }
     g_Quant_init++;
}

only when g_Quant_init count reaches 0 should it delete!

**Comment by zigguratvertigo** [comment]
Seems to work so far! :)

**Comment by zigguratvertigo** [comment]
A bit of a request here, but ultimately it would be amazing if there was a way to not rely on such Initialize()/Shutdown() methods at all, and simply call the CMP_Convert(...) to compress. Or some other kind of mechanism where we can contain calls to CMP_ locally, per thread. In our case we have to call such init/shutdown functions at the very beginning of our execution model, where we can spawn a chain of operations that might include compression (or not), so it's a bit unfortunate to have to initialize Compressonator at such a level, where we might compress stuff or not.

**Comment by NPCompress** [comment]
A mutex on Quant_Init() is required to guarantee that dynamic memory initialization is done on the first thread call and no other thread is attempting to call Quant_Deinit() at the same time. Muxtex will initially reduce performance and then resume back when done. It’s best to avoid these where possible.

The other approach is to not have the memory dynamically allocated. This will avoid the issue, however the memory allocation is large and will always be present in you code.

To enable this simply build the code by commenting out #define USE_TRACE_WITH_DYNAMIC_MEM

I have added a mutex to Quant_Init() and so far it seems to be working without the need for
CMP_InitializeBCLibrary() and CMP_ShutdownBCLibrary();

A newer more compute compliant version of BC7 and BC6H are been developed and should be more suitable towards your needs. A feature notification will be updated when these codecs are scheduled for release.

**Comment by zigguratvertigo** [comment]
Any idea / quick workarounds for the cause of this multi-threaded related crash? In this case, related to BC6H.

![image](https://user-images.githubusercontent.com/1844966/30970034-6e4827ee-a464-11e7-826a-bd2185b3fd47.png)

As mentioned here, did pass bDisableMultithreading==true and mNumThreads==1. Might be related?

![image](https://user-images.githubusercontent.com/1844966/30970103-984d2e2c-a464-11e7-8e85-c387c6751a90.png)

If I disable our multi-threading code, where everything go through the same parallel_foreach loop (just like mentioned previously), then everything is fine.

**Comment by NPCompress** [comment]
Looking into this, suggest trying a quick fix sucha as:

CodecError CCodec_BC6H::CFinishBC6HEncoding(void)
{
    if(!m_LibraryInitialized)
    {
        return CE_Unknown;
    }

    if (m_EncodeParameterStorage)
    {
        if (m_Use_MultiThreading)
        {
            // Wait for all the live threads to finish any current work
            for (DWORD i = 0; i < m_LiveThreads; i++)
            {
                // If a thread is in the running state then we need to wait for it to finish
                // its work from the producer
                while (m_EncodeParameterStorage[i].run == TRUE)
                {
                    Sleep(1);
                }
            }
        }
    }
    return CE_OK;
}


Since it seems that codec has already deleted the storage prior!

**Comment by NPCompress** [comment]
Is your BC6H Codec the latest code? seems like its an older revision!

**Comment by livinamuk** [comment]
You mentioned calling `CMP_InitializeBCLibrary()` and then `CMP_ShutdownBCLibrary()` to achieve thread safety when loading BC7. I'm not having any luck with this. Do I still only call `InitializeCMPFramework()` once at program init?
