### ISSUE TITLE
-DOPTION_BUILD_KTX2=OFF has no effect

### ISSUE THREAD

**Issue by bekorn** [GPUOpen-Tools/compressonator#261]
OPTION_BUILD_KTX2 has no effect because it is overwritten by this section that only depends on CMake version(?).
https://github.com/GPUOpen-Tools/compressonator/blob/0bea29d5ab01c688c8408edf50a8f13dfe7a915b/CMakeLists.txt#L119-L123

Maybe it can be replaced with this?
```CMake
if(OPTION_BUILD_KTX2 AND ${CMAKE_VERSION} VERSION_LESS_EQUAL "3.14.0")
    message(WARNING "Turning off KTX2 because current CMake version is not supported")
    cmp_option(OPTION_BUILD_KTX2 "Build CLI KTX2 Support" OFF)
endif()
```

Though even with this change, there are several other points where KTX2 is included without checking the OPTION_BUILD_KTX2. Is it okay if I create a patch that makes KTX2 actually optional? If yes, should I enable/disable KTX and KTX2 together?

**Comment by NPCompress** [comment]
@bekorn  Yes, let's make both enable/disable KTX and KTX2 together.

**Comment by bekorn** [comment]
Hi again. I think I've made the CMake -D arguments have an effect on the build (none were effective as I understand). You can check it here https://github.com/GPUOpen-Tools/compressonator/compare/master...bekorn:compressonator:improving_CMakeLists

However, I can't be sure if everything works, because I can't build the project because of all the dependencies that I don't have on my machine :/ Are there automated tests for this? Or can you test it? I can make a PR if that would be easier.
