### ISSUE TITLE
dds header flag DDSD_MIPMAPCOUNT always set

### ISSUE THREAD

**Issue by seragh** [GPUOpen-Tools/compressonator#266]
This when saving a texture with CMP_SaveTexture.

Probably when mips levels is 1 this flag shouldn't be set.

https://learn.microsoft.com/en-us/windows/win32/direct3ddds/dds-header

**Comment by denislevesqueAMD** [comment]
@seragh Thanks for reporting this and the other couple issues you've reported recently! We will be taking a look at these and resolving them in the next release.

**Comment by NavNTCMP** [comment]
@seragh  Issue addressed in v4.5 release

**Comment by seragh** [comment]
confirmed, thanks
