### ISSUE TITLE
Multithreading can't be disabled for BC6H

### ISSUE THREAD

**Issue by zigguratvertigo** [GPUOpen-Tools/Compressonator#27]
Hi,

Even if we pass dwnumThreads==1 and bDisableMultiThreading==false, BC6H compression still runs multithreaded.

// Compression settings
CMP_CompressOptions options;
memset(&options, 0, sizeof(options));
options.dwSize = sizeof(options);
options.fquality = AMD_CODEC_QUALITY_DEFAULT;
options.dwmodeMask = 0xCF;
options.dwnumThreads = 1;
options.bDisableMultiThreading = true;

**in CCodec_BC6H::CFinishBC6HEncoding(void)**

m_Use_MultiThreading == 1
and
m_LiveThreads == 8

**Comment by xooiamd** [comment]
Hi @zigguratvertigo , please try the latest commit and let us know if the issue still exist. Thanks!
