### ISSUE TITLE
MacOS Apple silicon support (Universal build)

### ISSUE THREAD

**Issue by neelmewada** [GPUOpen-Tools/compressonator#280]
The project doesn't build when targeting universal architecture on MacOS in Xcode. However, it builds just fine if we force x64 architecture. Is apple silicon support planned?

**Comment by denislevesqueAMD** [comment]
@neelmewada Thanks for the report! There are currently no plans to support Apple silicon in the near future.

**Comment by man-in-black382** [comment]
I recommend just compiling for Arm/x86 separately and then lipo'íng them together.

**Comment by neelmewada** [comment]
Hey @man-in-black382! Thanks, I was able to build for mac universal by manually removing the SIMD functions manually and using the default cpu function.
