### ISSUE TITLE
VS2015 solution doesn't actually build

### ISSUE THREAD

**Issue by TrianglesPCT** [GPUOpen-Tools/Compressonator#29]
The files half.h/cpp are missing, this is part of OpenEXR which isn't included in the download.

Downloading OpenEXR doesn't help since then it requires "toFloat.h" which also doesn't exist, apparently they assume you will use their clunky build system to generate it.

Perhaps provide a way to remove this dependency? Do you really need such a clunky dependency just for half float support?

**Comment by impakt73** [comment]
Try running "git submodule update --init --recursive" in the main directory.
That fixed it for me.
