### ISSUE TITLE
Library build instructions

### ISSUE THREAD

**Issue by reduz** [GPUOpen-Tools/Compressonator#30]
For Godot, we are interested in bundling only the compressor code inside of the engine. Is it available as a static library that can be compiled on Linux, Windows and OSX?

**Comment by NPCompress** [comment]
Hi Reduz, 
Yes, it can be linked in as static libs. 

They can be built from source or you can use the libs from the installers lib directories. The source for the libs are at the root folder under Compressonator/Source and Compressonator/Header 

On windows you can build from CompressonatorLib.sln (and see the list of all file dependencies),
cmake files are also provided to build for other OS's see example under Compressonator/make
Eventually we will be removing VS project files and just use cmakes.

At this time support for OSX is not fully qualified!.

We do not have "scon" build files for Compressonator  but it would be of interest if they were available.
