### ISSUE TITLE
R and B channels are switched for ETC_RGB compression

### ISSUE THREAD

**Issue by imhuwq** [GPUOpen-Tools/Compressonator#34]
If you compress a image using ETC_RGB, then the output DDS have red and blue channels switched. I have tested it on my and several of my colleagues' Andriod phones in WebGL.   
If I switch the R and B before the compression, then I get the expected DDS file.   
Havn't tested in ETC2.  
Should this be fixed?

**Comment by NPCompress** [comment]
Hi @imhuwq  in our current SDK codecs [ETC1, ETC2, BC1 to BC5 (DXT1..DXT5),..] are expecting image source as BGR as input, and new codecs [BC6H, BC7 and ASTC] are expecting RGB as source input. We are developing an updated SDK that will unify the input expected as RGB.  The swizzle of R & B channels are handled in GUI and CLI applications. Our Texture Loaders all load into RGB channels.

**Comment by imhuwq** [comment]
Hi @NPCompress , thank you for your reply.   
If I understand you right, the switch of R and B are expecting behaviors, not a bug.    
However, do the DXT series switch the R and B too? In my test, they work fine as R and B not be switched.

**Comment by umustbeloggedintododat** [comment]
I got this error too, how do I fix it?

**Comment by umustbeloggedintododat** [comment]
:(


![1987_porsche_962c_ext etc_dds_ARGB_8888](https://user-images.githubusercontent.com/54049600/95642252-5517b300-0a75-11eb-845c-748b577cd818.png)
