### ISSUE TITLE
When converting Images to KTX file format internal formats don't match image type.

### ISSUE THREAD

**Issue by EuwTech** [GPUOpen-Tools/Compressonator#35]
When I coerced Compressenator into saving a file that was originally a TGA to a KTX file format I get a minor error in the header:
The glInternalFormat in the KTX header is being set to the same value as the glFormat such as GL_RGBA. But the KTX format spec says this should be the  sized internal format such as GL_RGBA8.
Here's a link: (they include a link to the format table)
https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/#2.6

**Comment by xooiamd** [comment]
hi @EuwTech , you are right. glInternalFormat should only be equal to glFormat if the context does not support sized formats. Change to GL_RGBA8 just posted to the master branch. Let us know if you still encounter the error. Thanks!
