### ISSUE TITLE
Missing d3d12.dll error dialog on Windows 7 x64

### ISSUE THREAD

**Issue by onemanmmo** [GPUOpen-Tools/Compressonator#37]
The documentation on Compressonator x64 2.7.3568 led me to believe it works on Windows 7, however using the CLI version, it pops up a dialog "CompressonatorCLI.exe - System Error - The program can't start because d3d12.dll is missing from your computer. Try reinstalling the program to fix this problem."  Since DirectX 12 isn't available for Windows 7 this makes the CLI version useless for scripting. The GUI version shows the same dialog.  Otherwise the program seems to work fine.

**Comment by NPCompress** [comment]
Hi @onemanmmo 

Since you are using windows 7. I would suggest you try deleting or move to another folder the preview 3D model viewer extension from plugins folder
 glTF_DX12_EX.dll   

Both CLI and GUI applications try to load all extensions in the plugin folder at startup

**Comment by onemanmmo** [comment]
That worked, thank you!

**Comment by mirh** [comment]
This is now happening with `ModelViewer_DX12.dll` instead.

**Comment by NPCompress** [comment]
@mirh  Thanks for notification. Please do the same as responded on Jan 9, 2018. The Plugin loader code is been updated to not load runtime DLL's for windows when application starts up. It will register the files prior using only file read (not using runtime dll loading)  and determine OS compatibility, this will fix issues as you are  experiencing for Windows 7. This will be available on next release.
