### ISSUE TITLE
Support for KTX float images

### ISSUE THREAD

**Issue by UX3D-nopper** [GPUOpen-Tools/Compressonator#38]
Especially for HDR cube maps with its mip map levels.

**Comment by xooiamd** [comment]
hi @UX3D-nopper , Compressonator KTX plugins do support KTX float with miplevels as shown in the [KTX.cpp](https://github.com/GPUOpen-Tools/Compressonator/blob/master/Compressonator/Applications/_Plugins/CImage/KTX/KTX.cpp) file. Can you provide further details of the issue and sample float images so we can look into it further? Thanks!

**Comment by UX3D-nopper** [comment]
Please find attached following zipped KTX image file:

[studio_COOKTORRANCE.zip](https://github.com/GPUOpen-Tools/Compressonator/files/1661944/studio_COOKTORRANCE.zip)

It's a cube map, having mip maps and four float color channels.

Could not compress it and I think it did also crash during encoding/compressing.

**Comment by UX3D-nopper** [comment]
The cube map is generated from a black-white studio HDR image. There is "black" content in -Y and +Z. In all other cases, it has black/white patterns.
E.g. open with PVRTex tool, and u will see that there is content in other mip levels as well.

**Comment by xooiamd** [comment]
Thanks for reply @UX3D-nopper . We are working on this and will post update soon. thanks

**Comment by xooiamd** [comment]
hi @UX3D-nopper , loading the attached sample still end up with unexpected file ending error. According to the KTX file structure [here](https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/#1) , for non-array cubemap, the [ImageSize](https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/#2.16) that retrieved from the file is 25165824 bytes , using this ImageSize and iterate through the 6 faces in level 1, there is file end error on 2nd face iteration which expected to read in 25165824bytes but it hit EOF and read only 8388612 bytes. I am not sure why PVRTex can view the file, but I am trying to fix according to KTX file spec. Please correct me if my understanding of the file load is wrong. Thanks!

**Comment by UX3D-nopper** [comment]
Hmm, I am using gli for loading and storing KTX files: http://gli.g-truc.net/0.8.2/index.html
Maybe Christophe has a comment on this? @Groovounet

**Comment by xooiamd** [comment]
hi @UX3D-nopper and @Groovounet, a quick look at the loop used in gli loadktx as shown below:

for(texture::size_type Level = 0, Levels = Texture.levels(); Level < Levels; ++Level)
		{
			Offset += sizeof(std::uint32_t);

			for(texture::size_type Layer = 0, Layers = Texture.layers(); Layer < Layers; ++Layer)
			for(texture::size_type Face = 0, Faces = Texture.faces(); Face < Faces; ++Face)
			{
				texture::size_type const FaceSize = Texture.size(Level);

				std::memcpy(Texture.data(Layer, Face, Level), Data + Offset, FaceSize);

				Offset += std::max(BlockSize, glm::ceilMultiple(FaceSize, static_cast<texture::size_type>(4)));
			}
		}

Seems like they just ignore "UInt32 imageSize" in the KTX file structure by doing the Offset += sizeof(std::uint32_t); and assume the image size for that face is "texture::size_type const FaceSize = Texture.size(Level);" which is equal to the miplevel (2D texture) image size which might be wrong.  And seems like the same issue is found on gli savektx as well where the imageSize is ignored. 
Thanks,

**Comment by Groovounet** [comment]
Here is the spec and it looks like GLI could be doing something wrong for cubemaps. This said, with HDR formats, I understand that the KTX should not have any padding...

> 2.16 imageSize
> For most textures imageSize is the number of bytes of pixel data in the current LOD level. This includes all z slices, all faces, all rows (or rows of blocks) and all pixels (or blocks) in each row for the mipmap level. It does not include any bytes in mipPadding.
> 
> The exception is non-array cubemap textures (any texture where numberOfFaces is 6 and numberOfArrayElements is 0). For these textures imageSize is the number of bytes in each face of the texture for the current LOD level, not including bytes in cubePadding or mipPadding.
> 
> 2.17 cubePadding
> For non-array cubemap textures (any texture where numberOfFaces is 6 and numberOfArrayElements is 0) cubePadding contains between 0 and 3 bytes to ensure that the data in each face begins at a file offset that is a multiple of 4. In all other cases cubePadding is empty (0 bytes long).
> 
> 2.18 mipPadding
> Between 0 and 3 bytes to make sure that all imageSize fields are at a file offset that is a multiple of 4.

**Comment by UX3D-nopper** [comment]
Thanks a lot for looking at this.
