### ISSUE TITLE
Gamma Lost compressing PNG -> DDS

### ISSUE THREAD

**Issue by onemanmmo** [GPUOpen-Tools/Compressonator#39]
I have a bunch of gamma 1.0 (linear) PNG files (they have the GAMA chunk in them) for normal maps.  When I convert them to DXT1 DDS files, the DDS files don't have the DX10 header which specifies that the data is linear.  Am I missing a switch somewhere?

**Comment by xooiamd** [comment]
hi @onemanmmo , the [DDS_HEADER_DXT10](https://msdn.microsoft.com/en-us/library/windows/desktop/bb943983(v=vs.85).aspx) structure does not specifies explicitly if the data is a linear data or gamma corrected. You can try to convert to the dxgiformat that you desires by specifies the correct CMP_Format during the conversion. The dxgiformat in the DX10 header might not support linear data as described [here](https://msdn.microsoft.com/en-us/library/windows/desktop/hh972627(v=vs.85).aspx) "..integer-valued display formats (such as DXGI_FORMAT_B8G8R8A8_UNORM_SRGB, DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM, and so on) always contain sRGB gamma-corrected data. Float-valued display formats (currently only DXGI_FORMAT_R16G16B16A16_FLOAT) contain linear-valued data. "  . Hope this information helps. Thanks.
