### ISSUE TITLE
Different process for ATC compression ?

### ISSUE THREAD

**Issue by JiDW** [GPUOpen-Tools/Compressonator#4]
Hello,

Before Win10, we were using the old compressonator (1.5) as a CLI inside our own building tools, in java.

We are now trying to use the new version but it looks like this compressonator uses a different process to compress images with ATC. It means that when we try to loop and compress our files, we can't use "process.waitFor();" to know when the compressonator is done with a file.

We do not have this issue for DXT.

Is it a bug ? If not, how can we know when a compression is over ?

Thanks a lot.

**Comment by NPCompress** [comment]
Are you using the CompressonatorCLI.exe or using the API in the SDK?

There should be no difference in operation when using the CompressonatorCLI.exe for textures with ATC or DXT formats.

The command line app returns an exit code 0  for success or -1 on error

**Comment by JiDW** [comment]
The CLI. At this moment, we get an exit code 0 before the compression is effectively taking place.

**Comment by JiDW** [comment]
Well, I'm not a smart man. This is obviously linked to the another issue and I needed half an hour to connect the two of them : https://github.com/GPUOpen-Tools/Compressonator/issues/5

It exit with a code 0 even if it didn't create a file.

**Comment by NPCompress** [comment]
RAW output file format is not currently supported and will be addressed this issue along side the exit code 0 for no file generation.

Thanks for bring this to our attention

**Comment by NPCompress** [comment]
V2.4 CLI now exits with proper error codes.
Support for ATC codec has been improved.
