### ISSUE TITLE
New DX11 BC7 options not supported

### ISSUE THREAD

**Issue by m0lz** [GPUOpen-Tools/Compressonator#41]
Will you be supporting the new DX11+ variations of BC7, such as Linear Fine ?

https://software.intel.com/sites/default/files/managed/e9/08/betaFormats.png

( Image url is from the Intel Texture Works page here https://software.intel.com/en-us/articles/intel-texture-works-plugin )

**Comment by NPCompress** [comment]
@m0lz  Thanks for you inquiry, We will look further into the specifications for Liner Fine specified in the link you provided. 

For BC7 we have the following support in our File loaders and GPU Decoder plugins (which also support DX11+)

DXGI_FORMAT_BC7_TYPELESS.
DXGI_FORMAT_BC7_UNORM.
DXGI_FORMAT_BC7_UNORM_SRGB.

For Compression  we have  the following translation:
DXGI_FORMAT_BC7_TYPELESS  to  CMP_FORMAT_BC7 

Options for mapping 
DXGI_FORMAT_BC7_UNORM           to  CMP_FORMAT_BC7_UNORM
DXGI_FORMAT_BC7_UNORM_SRGB to  CMP_FORMAT_BC7_SRGB

will be added.

**Comment by m0lz** [comment]
Thank you, but just to be sure you are getting the right one, its the second BC7 entry on the linked [screenshot](https://software.intel.com/sites/default/files/managed/e9/08/betaFormats.png) which reads ..

BC7 8bpp Fine (Linear DX11+)

**Comment by xooiamd** [comment]
hi @m0lz ,  BC7 8bpp Fine is same as Fast but using longer compression time for better result. We do have this support using the "Quality" parameter in the compressonator which will take longer time for compression if you set to higher quality value. The quality value range is 0 (Poor Quality) to 1 (High Quality) with default set at 0.05 (Fast). If you are using compressonatorcli app, you can try running the command line "CompressonatorCLI.exe   <input filename> <output filename> -fd BC7  -Quality 0.0500"  (this is using the default 0.05 value). if you are using compressonator SDK, please refer to the [example](https://github.com/GPUOpen-Tools/Compressonator/blob/master/Compressonator/Examples/Compressonator_Test.cpp)   on how to specify the quality value using CMP_CompressOptions variable. Hope this helps. Thanks
