### ISSUE TITLE
Can provide ETA of Compressonator 3.0 announced at GDC?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Tools/Compressonator#42]

**Comment by NPCompress** [comment]
@oscarbg 
We are running QA tests and expect the release to be end of April mid-May.
What features of this release are you most interested in?

**Comment by oscarbg** [comment]
Hi,
thanks for the update..
I'm interested in testing the new "mesh optimization" & compression..
gltf is already supported and with new mesh compression support seems natural to ask if it will support when exporting mesh to GLTF using the optional & new GLTF draco mesh compression extension?
