### ISSUE TITLE
How to visualize the quality impact of various compression technologies?

### ISSUE THREAD

**Issue by pps83** [GPUOpen-Tools/Compressonator#43]
> Compressonator is a set of tools to allow artists and developers to more easily create compressed texture assets or model mesh optimizations and easily visualize the quality impact of various compression and rendering technologies

So... I download it, run it, open "BC7 Compression" sample project from welcome page. I see a boat there, I see other images... but I do not see how to "easily visualize the quality impact of various compression and rendering technologies". WTF?! I "add destination settings", but then I want to be able to flip different formats and see it right there the difference.

For example, I zoom the boat 10x, and I press ASTC format in the left project window and I want the same picture to be at the same position and zoom level but shown after it was compressed. Or there is different meaning to "easily visualize", or I'm not doing something right?

**Comment by NPCompress** [comment]
@pps83 
Compressonator V2.7 has post process visualization using ImageDiff with analysis stats as described in this link https://github.com/GPUOpen-Tools/Compressonator/wiki/Image-Diff-Analysis, The feature you just described is available in V3.0 release expected in a few weeks, where after compression both images of the original and compressed (including image diff and original)  overlays can be viewed, zoomed and flipped back and forth using keyboard or mouse.

**Comment by pps83** [comment]
As a minor suggestion feature request I'll add this: can you please make it possible to scroll formats for an image using mouse wheel?
It could be implemented as a dropdown box "view as" on the toolbar where you could simply change selection of texture compression format and see right away the image how it would look like in different texture codec selected in "view as" dropdown. If it's not some broken dropdown box (most likely should be ok in qt) then it would also work with mouse wheel: simply hovering mouse over the dropdown and using scroll wheel would allow you to quickly change between different texture formats.
 Here's the use case I'm interested in. For example, I have an image in left pane and then I zoom to some specific area of interest and then using scroll wheel I would flip back and forth different texture formats and always see the same zoomed-in area. If image in the left pane does not have selected output codecs then "view as" should show all possible texture formats to flip through; if image has output formats defined, then "view as" would show only these formats of interest.

**Comment by NPCompress** [comment]
@pps83 

Thanks for your feature suggestions, these ideas will be reviewed for future release
