### ISSUE TITLE
ETC2 - Support for sRGB and EAC still missing

### ISSUE THREAD

**Issue by thokra1** [GPUOpen-Tools/Compressonator#44]
The release notes for v2.3 stated that "Alpha and SRGB based ETC2 support will be supplied in future releases". As of v2.7 they still seem to be missing, which is a shame, because some tests I ran suggests that compression speeds for ETC2_RGB seem to exceed all other viable tools out there, even etc2comp.

Any news on this?

**Comment by NPCompress** [comment]
@thokra1
Thanks for the comments on ETC2_RGB. We are currently evaluating ETC1 and ETC2 codec for additional support, which includes evaluating existing implementations such as ETC2Comp, FastTC, ...
Our development schedule for new texture compression codecs will be posted after v3.0 release, which is expected mid May.

**Comment by NPCompress** [comment]
@thokra1
Release schedule for ETC has been posted

**Comment by thokra1** [comment]
Nice, ty! :)
