### ISSUE TITLE
Misssing libraries in 3.0 release for Linux

### ISSUE THREAD

**Issue by kraghot** [GPUOpen-Tools/Compressonator#46]
The release tar of 3.0 seems to be missing the following libraries:

- `libjpeg.so.62`
- `libpng12.so.0`
- `libpangox-1.0.so.0`

On Ubuntu 18.04 the last one can be easily resolved by installing `libpangox-1.0-0` package, however the other two are older than the ones in the repository and as a result do not work.

**Comment by reanimastudios** [comment]
I'll put in for also the need of libboost 1.58. Debian hasn't seen that in a long time, ala presently Sid is 1.63 and Stretch [Stable] is at 1.62.

**Comment by xooiamd** [comment]
Hi, as our CLI test only run on 16.04, thanks for bringing this to our attention! We have updated the release with the missing libraries. Thanks!
