### ISSUE TITLE
CompressonatorLib.sln doesn't compile out-of-box

### ISSUE THREAD

**Issue by Dolphiniac** [GPUOpen-Tools/Compressonator#47]
I pulled the repo today to test the BC6H_SF16 encoding (I need to make a modification to test exactly one mode against some data), and the sln doesn't compile in VS2015.

It first complains that CMP_BYTE is not defined in GT_Encode.h and GT_Decode.h, then claims that CMP_NULL does not exist, which is used everywhere.  I fixed those by hooking in Compressonator.h and #defining CMP_NULL to 0, but the GT code also depends on "GTEncodeThreadParam", which doesn't seem to exist as a symbol anywhere in the repo.

Since I don't need the GT code, I'm just going to piecemeal comment the offending code, but I felt that maybe these issues should be addressed for future users.

**Comment by xooiamd** [comment]
hi @Dolphiniac , thanks for reporting. CompressonatorLib should be compile now. Let us know if there is any issues. Thanks!
