### ISSUE TITLE
No outputed file when you try to create a file without .DDS ext for ATC

### ISSUE THREAD

**Issue by JiDW** [GPUOpen-Tools/Compressonator#5]
When you try to compress a file with ATC but use in the command line something else than a .DDS extension, it fails silently.

Because of android devices, it is needed to have both DXT and ATC compressed textures available in your app, so renaming ATC DDS files to something else (like .atc) is quiet common practice.

Anyway, the CLI should at last produce an error, ot better, accept any kind of extension, like the 1.5.

Regards.

**Comment by NPCompress** [comment]
Hi 

After further investigation, it has been determined that the command line application attempts to reinterpret the .atc extension as a custom file format that is typically handled by user supplied 3rd  party Qt plug ins. This mechanism allows users to add output or input file formats for uncompressed image formats not handled by CLI by default. As in your case this extension was not available and the Qt plugin mechanism returned a error code that was not picked up by CompressonatorCLI and simply continued without error. This has been fixed and an updated will be posted soon. (The application will exit with -1 for unknown file extensions)

For your use case, you could use the new .ktx file extension that is supported on Windows and Linux. The KTX file format supports ATC and DXT as defined in cKTX.h source code, Additional formats cans be added

To use .atc as a RAW un-formatted file output (have the ATC block data with no header info) a new command line option will have to be added that will prevent the application from attempting to use a unknown extension as a uncompressed image file output.

Example:
CompressontorCLI sourceImage,bmp compressed.atc -RAW -fd ATC_RGB

compressed.atc will contain ATC formatted compressed image blocks

If having this option is useful for your case or further modification is needed, please let us know.

**Comment by xooiamd** [comment]
hi @JiDW do you think the option as suggested by the example given by NPCompress CompressontorCLI sourceImage,bmp compressed.atc -RAW -fd ATC_RGB is useful for your case? currently the CLI exit with error for unsupported extension.
Also regarding your comment on 1.5 CLI accept any kind of extension, what command you run on CLI 1.5 version? I tried TheCompressonator.exe -convert image.png compressed.atc -format ATC but it doesn't produce any compressed.atc file. it only produces compressed file if i rename the .atc to .dds.  Thanks.

**Comment by NPCompress** [comment]
Available in V2.4 release: When no extension is supplied to output file, a default DDS extension will be applied.
