### ISSUE TITLE
Decompress Mipmaps from DDS format in CLI

### ISSUE THREAD

**Issue by jdperos** [GPUOpen-Tools/Compressonator#50]
Decompressing a DDS file through the command line interface only decompresses MipLevel 0. Does the CLI support decompressing all mip levels for a DDS file?

**Comment by NPCompress** [comment]
@jdperos 

CLI supports decompression of all MipLevels from compressed DDS files.

Some examples on how to generate MipLevels and then decompress using CLI

To generate a compressed BC7 DDS file with up to 9 MipLevels 
CompressonatorCLI.exe  -fd BC7 -miplevels 9 .\images\Ruby2.bmp Ruby2_bc7.dds

To decompress the BC7 DDS file, target file must support MipLevels (example back to DDS)
CompressonatorCLI.exe  Ruby2_bc7.dds Ruby2_decomp.dds

if you specified a file like .png only MipLevl 0 will be saved
CompressonatorCLI.exe  Ruby2_bc7.dds Ruby2.png

**Comment by jdperos** [comment]
Ah, I see! I was hoping to be able to save all Mip levels to a non-DDS format (as different images). I can make conversion to other DDS compressions work, though.
