### ISSUE TITLE
v3.0 Doesn't build on mac

### ISSUE THREAD

**Issue by merihtaze** [GPUOpen-Tools/Compressonator#51]
The mac build isn't working with the latest upgrade. I'm able to build successfully when I checkout a branch with the 2.7.3568 with SHA# 6edae582ff7550ddab9f4df2186e74f7903ed73e. But not with the latest code. Can you please fix it?

**Comment by xooiamd** [comment]
Hi @merihtaze , thanks for reporting this, we are looking into this and will let you know once fixed.

**Comment by xooiamd** [comment]
Hi @merihtaze, ktx.h header files in mac seems requires the GL/glcorearb.h , you can try to get that from http://www.opengl.org/registry/api/GL/glcorearb.h and placed in the same folder as GL, i.e.
_sudo wget -P /usr/local/include/GL http://www.opengl.org/registry/api/GL/glcorearb.h_
and the mac build also need some minor changes in some of the cmake scripts to add definitions same as linux build. Please find attached cmakelist.txt (one to replace the CMakeList.txt in Compressonator/Make and another one to replace the CMakeList.txt in Compressonator/Applications/CompressonatorCLI/Make/). Please copy replace and rename the files accoridingly then run the build shell again. Let us know if you encounter issues in the mac build. Thanks!
[CMakeLists_replace_in_CLI_make.txt](https://github.com/GPUOpen-Tools/Compressonator/files/2333516/CMakeLists_replace_in_CLI_make.txt)
[CMakeLists_replace_in-Compressonator-Make.txt](https://github.com/GPUOpen-Tools/Compressonator/files/2333519/CMakeLists_replace_in-Compressonator-Make.txt)

**Comment by merihtaze** [comment]
That did solve the build problems. Thank you for the help!
