### ISSUE TITLE
CompressonatorCLI 2.7.3568 doesn't work on Mac

### ISSUE THREAD

**Issue by merihtaze** [GPUOpen-Tools/Compressonator#52]
I've built the CLI on my mac with the SHA# 6edae582ff7550ddab9f4df2186e74f7903ed73e but when I run it, I keep getting the same error: "Error: saving image or destination format is unsupported by Qt"

I've tried to use different images(png, jpg, bmp), different compressions but keep getting the same error:

$ ./CompressonatorCLI -fd DXT1 test.jpg test.dds
Source Texture size = 518400 Bytes, width = 360 px  height = 360 px
Destination Texture size = 64800 Bytes   Resulting compression ratio = 8.00:1
Compression progress = 99 Error: saving image or destination format is unsupported by Qt

$ ./CompressonatorCLI -fd DXT1 test2.jpg test.dds
Source Texture size = 1048576 Bytes, width = 512 px  height = 512 px
Destination Texture size = 131072 Bytes   Resulting compression ratio = 8.00:1
Compression progress = 99 Error: saving image or destination format is unsupported by Qt

$ ./CompressonatorCLI -fd DXT5 test2.jpg test.dds
Source Texture size = 1048576 Bytes, width = 512 px  height = 512 px
Destination Texture size = 262144 Bytes   Resulting compression ratio = 4.00:1
Compression progress = 99 Error: saving image or destination format is unsupported by Qt

$ ./CompressonatorCLI -fd ETC_RGB test2.jpg test.dds
Source Texture size = 1048576 Bytes, width = 512 px  height = 512 px
Destination Texture size = 131072 Bytes   Resulting compression ratio = 8.00:1
Compression progress = 99 Error: saving image or destination format is unsupported by Qt

$ ./CompressonatorCLI -fd ETC_RGB test.png test.dds
Source Texture size = 1048576 Bytes, width = 512 px  height = 512 px
Destination Texture size = 131072 Bytes   Resulting compression ratio = 8.00:1
Compression progress = 99 Error: saving image or destination format is unsupported by Qt

Can someone please help me?

**Comment by xooiamd** [comment]
Hi @merihtaze , Compressonator is using v5.7 or less for build, if you are using "brew install qt" in your mac, you might end up installing v5.11 or later. Can you try run "brew search" to look for which qt package is available for your mac system? if you have qt@5.5, try install and use that package instead. Hope this helps getting rid of the error. Let us know if you still encounter further issues. Thanks!

**Comment by merihtaze** [comment]
Thank you. Using qt@5.5 fixed the issue.
