### ISSUE TITLE
v3.0 Compressonator CLI in Linux incorrect working

### ISSUE THREAD

**Issue by GlebGeracimenko** [GPUOpen-Tools/Compressonator#53]
![screenshot from 2018-08-30 11-54-51](https://user-images.githubusercontent.com/8939518/44841217-86ddaf00-ac4b-11e8-9ebb-9d49c495e5be.png)

scene.gltf file was downloaded from https://sketchfab.com/models/294e79652f494130ad2ab00a13fdbafd
dest.gltf is empty file created with me.

What could be the problem?

**Comment by xooiamd** [comment]
hi @GlebGeracimenko , thanks for reporting this. As mentioned in v3.0 release note: 
"Model Mesh Compression for obj files
Compresss models for faster download using Draco .drc files
Set quantization bits for POSITION, NORMAL, TEX_CORD and other GENERIC attributes"
So the draco compression only support obj file in v3.0 binary. 
For gltf file support in mesh compression, please pull down latest from master branch and run initsetup_ubuntu.sh then buildCLI_ubuntu_cmake.sh in the Compressonator/Applications/CompressonatorCLI/Make/ folder to get the CompressonatorCLI binary that support gltf file draco mesh compression. Note: the gltf file mesh processing support single meshes for now. Thanks,
