### ISSUE TITLE
Precompiled CompressonatorCLI for Mac OSX

### ISSUE THREAD

**Issue by MartyMaro** [GPUOpen-Tools/Compressonator#57]
I think it would be great if the release section would also provide a pre-compiled version of CompressonatorCLI. 

Is this possible?

**Comment by drewcassidy** [comment]
+1. I've spent several hours today trying to compile it with no luck...

**Comment by xooiamd** [comment]
hi @drewcassidy , currently only build in Mac Sierra is tested on v2.7 and [here](https://github.com/GPUOpen-Tools/Compressonator/blob/master/Compressonator/Applications/CompressonatorCLI/Make/readme.txt) is the steps to build. thanks

**Comment by xooiamd** [comment]
[CMPv3.zip](https://github.com/GPUOpen-Tools/Compressonator/files/2944330/CMPv3.zip)

Hi, please find attached precompiled CompressonatorCLI for Mac. Thanks.
