### ISSUE TITLE
CLI options related to mipmap generation could use documentation/clarification

### ISSUE THREAD

**Issue by rotoglup** [GPUOpen-Tools/Compressonator#6]
The `-mipsize` could have better documentation.

Isn't possible to let the tool compute the number for a complete mipmap chain ?

It seems that there are issues when the given values are wrong, leading to unclear error messages such as, for a 1024x1024 RGB8 TIF :

```
CompressonatorCLI.exe xxx.TIF xxx.ktx -fd ETC2_RGB -Quality 1.0000 -mipsize 1024
```
gives
```
Compression progress = 100
Error(0): KTX Plugin ID(1) saving file = xxx.ktx
Error: saving image or format is unsupported
```
while
```
CompressonatorCLI.exe xxx.TIF xxx.ktx -fd ETC2_RGB -Quality 1.0000 -mipsize 512
```
works fine.

Could it be related to the compression format block size ?

**Comment by rotoglup** [comment]
Hmm, in fact, `-mipsize` does not seem to provoke mipmap generation. 
`-miplevels` does.

I'm somehow lost in these options :)

**Comment by NPCompress** [comment]
-mipsize option attempts to generate mipmap levels that will reduce to the specified minimum image dimension

in your case if original image is 1024x1024 and you specify 512 is will generate a 1012x1024 image and 512x512 image for compression

while 

-miplevels specifies the number of divisions by 2 that are applied to the original image

512x512  is miplevel 1
256x256  is miplevel 2
128x128  is miplevel 3

**Comment by rotoglup** [comment]
Thanks for your quick reply, I made a few tests to try to get this into my head.

So ` -miplevels` tells the number a mipmap levels the output will contain :
* with a 1024x1024x24 input
* `CompressonatorCLI.exe rainbowd.TIF -fd RGB_888 -miplevels 3 c:\temp\rainbowd.dds`, will have 3 mipmaps (1024, 512, 256), logical
* `CompressonatorCLI.exe rainbowd.TIF -fd RGB_888 -miplevels [10..12] c:\temp\rainbowd.dds` will only have 10 mipmaps (1024, 512, 256, ..., 2)
* so it seems that with something like `-mipmaps 32`, you'll get a complete mipmap chain - except for the last missing 1x1 mipmap - _is this by design_ ?

And `-mipsize` instructs to generate mipmaps and stop _before_ the specified size :
* with a 1024x1024x24 input
* `CompressonatorCLI.exe rainbowd.TIF -fd RGB_888 -mipsize 256 c:\temp\rainbowd.dds`, will have 2 mipmaps (1024, 512)

Did I get it ?

**Comment by NPCompress** [comment]
"Did I get it:" Yes.
"is this by design?": No it should also given you 1x1 mipmap also.
"stop _before_ the specified size" : it should have given you a mipmap at that size.

We will look into these items and update on next revision.

As you have also figured out: the current ktx files implementation in the code does not support miplevels and is only available for  DDS files

**Comment by rotoglup** [comment]
> We will look into these items and update on next revision.
ok ! no wonder I was somehow confused ;)

> As you have also figured out: the current ktx files implementation in the code does not support miplevels and is only available for DDS files 
ok, as it was not clear in the doc, I hope you don't mind I added another issue #7 for reference to anyone like me, who hopes to generate complete KTXs ;)

**Comment by xooiamd** [comment]
hi, the latest commit on master branch will give you 1x1 mipmap and -mipsize now will stop at specified size.  thanks.
