### ISSUE TITLE
Support for cubemaps and arrays

### ISSUE THREAD

**Issue by gabdube** [GPUOpen-Tools/Compressonator#61]
As far as I'm aware, compressonator cannot compress multiple images into a single KTX file using texture arrays or cube maps. Is there any plan to support those features (at least on the CLI)?

For example, PVRTextool support this by passing the following parameters:

```
-cube +X,-X,+Y,-Y,+Z,-Z <input-files>
-array <input-files>
```

**Comment by NPCompress** [comment]
@gabdube Compressonator code contains TT_CubeMap to handle this and our KTX lib used for file IO also contains code for handling them in ref to ktx_header (numberOfFaces). However the CLI does not expose any code for this, it will have to be added, in order for cube maps can be processed.

**Comment by gabdube** [comment]
Thanks for the lightning fast response. 

I will look into this. Hopefully I'll be able to implement it by myself if the bulk code is already there.
