### ISSUE TITLE
DXTC Swizzle Issue

### ISSUE THREAD

**Issue by AshwinKumarVijay** [GPUOpen-Tools/Compressonator#63]
Does the issue in #59 affect the releases as well?

**Comment by NPCompress** [comment]
Yes the issue #59 is in v3.1 release (Nov 16 2018) also, The fix ( Dec 6, 2018 )  is currently only in the master branch of the source . 

A note was posted on the main page:
** NOTE: The master SDK source has a DXTC swizzle fix, make sure any applications using source (v3.1 and older) are adjusted accordingly, BC6H and BC7 are not affected by this change, for details ref: Closed Issue #59**

**Comment by AshwinKumarVijay** [comment]
Yes, sorry, I was just making sure about that.

Thank you very much!

**Comment by tbotting** [comment]
Considering this now requires quite a nasty workaround (or manually compiling the source), it would be nice if the releases could be updated. @NPCompress
