### ISSUE TITLE
IMGAnalysis doesn't build with OpenCV 4.0

### ISSUE THREAD

**Issue by qsniyg** [GPUOpen-Tools/Compressonator#64]
`IplImage` has been deprecated from OpenCV 4.0, resulting in failure to compile IMGAnalysis.

**Comment by xooiamd** [comment]
hi @qsniyg, currently compressonator IMGAnalysis is using OpenCV 2.49 and the submodule is provided [here](https://github.com/GPUOpen-Tools/common-lib-ext-OpenCV-2.49/tree/7faf04812b1e241bd611c9ea3e0355eae2df2a54)  .  You can try 'git clone --recurse-submodules https://github.com/GPUOpen-Tools/Compressonator.git' to get the opencv dependency or for already cloned repo, you can try 'git submodule update --init --recursive' . Meanwhile please stay tuned for any furture update on the OpenCV dependency. Thanks.
