### ISSUE TITLE
MIPs generation from SDK

### ISSUE THREAD

**Issue by giordi91** [GPUOpen-Tools/Compressonator#66]
Good evening, thank you so much for providing the tool it is amazing.
I am using compressonator sdk as a part of my resource compiler and it works great, the only issue I have right now is being able to generate MIPs. I see the CLI supports it but it seems through a plugin and is not part of the compressonator lib itself. 

Is it not possible at all? Or would be possible to add for the future?

**Comment by NPCompress** [comment]
@giordi91 
Thank you for this comment, it is very much appreciated.  Yes, it is possible to add the MIP generation to the SDK. We are working on a newer SDK that is much more readily integrable with far less external dependencies and your request will be available in the next SDK update.

If it's not too much to ask, can you provide us with which compression codec (BCn, ETCn, ASTC..) is it that you are targeting and which file formats are been supported (DDS, KTX,...)?

**Comment by giordi91** [comment]
This is the formats I am supporting from my command line that forwards to the sdk:

`const std::unordered_map<std::string, CMP_FORMAT> STRING_TO_FORMAT{
    {"DXT1", CMP_FORMAT_DXT1},
    {"DXT3", CMP_FORMAT_DXT3},
    {"DXT5", CMP_FORMAT_DXT5},
    {"DXT7", CMP_FORMAT_BC7}};

const std::unordered_map<std::string, DXGI_FORMAT> STRING_TO_DXGI_FORMAT{
    {"DXT1", DXGI_FORMAT_BC1_UNORM},
    {"DXT3", DXGI_FORMAT_BC3_UNORM},
    {"DXT5", DXGI_FORMAT_BC3_UNORM},
    {"DXT7", DXGI_FORMAT_BC7_UNORM}};
const std::unordered_map<std::string, DXGI_FORMAT> STRING_TO_DXGI_FORMAT_GAMMA{
    {"DXT1", DXGI_FORMAT_BC1_UNORM_SRGB},
    {"DXT3", DXGI_FORMAT_BC3_UNORM_SRGB},
    {"DXT7", DXGI_FORMAT_BC7_UNORM_SRGB}};`

Realistically right now I am mostly using DXT1 for color and DXT5 for normals, all outputting DDS files. 
I am having some issues with some artifacts for normals as well from the SDK compared to the GUI, but I will open a different issue for that.

Thank you so much for the quick reply.
