### ISSUE TITLE
Can I use CLI to convert DDS normal map to Unity PNG normal map

### ISSUE THREAD

**Issue by stranger-games** [GPUOpen-Tools/Compressonator#72]
Hi,

I'm trying to convert DDS normal map to PNG normal map for use in Unity since PNG is more optimized for mobile than DDS.

The GUI doesn't seem to export to PNG, so I used CLI like the following.

    CompressonatorCLI.exe Normal.dds Normal.png

But the resulting PNG is greenish rather than blueish. I suspect something is wrong with the conversion. How to appropriately convert dds normal map to PNG normal map?

Thanks for advance.

**Comment by NPCompress** [comment]
@stranger-games 

Try these steps for the GUI
1 Add the DDS file(s) to the Project Explorer
2 Add destination settings
3 For Destination Options select Format ARGB_8888
4 This will enable Destination formats for PNG, etc..
5 Save the settings and process the file

![image](https://user-images.githubusercontent.com/18406717/58137660-0576e400-7c01-11e9-80bd-eed722b822f7.png)


For CLI you can try:

CompressonatorCLI.exe  -fd ARGB_8888 Normal.dds Normal.png

If you still have issues, please send a sample of your Normal.dds file for review.
