### ISSUE TITLE
Single colour BC7 compression improvement

### ISSUE THREAD

**Issue by DeanoC** [GPUOpen-Tools/Compressonator#74]
If if a block is a single colour its non-optimal due to it using mode 4 rather than 6.  Mode 4 has reduced colour bits compared to mode 6 so single colour blocks aren't as close then the original.

The reason is the quantiser gives a error of 0 to solid colour blocks, so it just uses the first mode which due to the remap table is current 4.

What I've done locally is to put mode 6 at the head of the remap table.
Its just a single line change,
change
uint32_t   blockModeOrder[NUM_BLOCK_TYPES] = {4 6, 3, 1, 2, 0, 7, 5 };
to
uint32_t   blockModeOrder[NUM_BLOCK_TYPES] = {6, 4, 3, 1, 2, 0, 7, 5 };

**Comment by NPCompress** [comment]
@DeanoC 
Thank you for the insight of improving BC7 Codec for color blocks. We have been working on a new SDK update and have been analyzing data for mode settings and performance improvements. You are correct in saying that various modes can be rearranged for more optimal performance. 

In addition to resetting the blockModeOrder, improvements can be made to the quantizer by adjusting the shaker loop settings, partition sizes, and exit thresholds. By default modes 4 & 5 are turned off in the CCodec_BC7 constructor m_ModeMask member var. Additional code is required to use these modes only when alpha channels are present in the compressed block as they tend to drop the overall quality when used.

We see that you have been working on a new library using Compressonator code. https://github.com/DeanoC/gfx_imagecompress.  This is good work.  
Did you unify the source to be RGBA input block for all codecs?
Can your code be licensed under MIT?

**Comment by DeanoC** [comment]
I've changed the license to MIT, will go through all my libraries and make MIT. TBH I never know which license to use so an ask helps me decide :)

Its early days for me with the codecs. I you can probably see I'm trying to have a easy library to access your awesome code :) I haven't yet done the code to generate the mode mask relevant to the input format, but it has the format info so it can restrict certainly modes when alpha is present. I see because your constructor be default never allow mode 4, the case I found doesn't happen in the original code base (6 was the first code selected by the default).

At the moment I just have an API entry per compression type per backend (at the moment there is only the AMD compressenator back end but ultimately would like to have a few others). Due to the way my image library works it should work for any (non compressed) input format but at the moment you pick the codec manually. The next step is picking the best codec based on the input format from various subset (Dx10 HW, Dx11 HW, Iphone, etc.). 

This is my first step of just integrating the code (no fast paths etc.) which is working for the BCx types. I only noticed the single colour because I was debugging (I'd forget to init_ramps() and was stepping through a single colour texture and noticed it was picking mode 4).
