### ISSUE TITLE
BC6H CPU Decoder bug

### ISSUE THREAD

**Issue by Zelex** [GPUOpen-Tools/Compressonator#76]
Files: https://send.firefox.com/download/dcc3a03777702c22/#ARpj0hUbj52fHzQkqv96Tw

If you image diff these two files with the CPU decoder, you will see occasional huge block errors. If however you switch to the DX12 decoder, the block errors are gone.

Thus, there seems to be some bug in the CPU decoder that doesn't match the hardware.

**Comment by NPCompress** [comment]
@Zelex  Thank you for reporting the issue. It is been investigated with issue 75 pull fix for bc6h decode.

**Comment by Zelex** [comment]
That was fast! :) will verify on next release
