### ISSUE TITLE
A little error in DXT1

### ISSUE THREAD

**Issue by liberty752** [GPUOpen-Tools/Compressonator#78]
This is the source image. I add the red arrow for focusing easily.
![企业微信截图_15688847173485](https://user-images.githubusercontent.com/1614519/65233486-7a055500-db05-11e9-92c3-1505239c9fdf.png)

And this is the preview which is after DXT1
![企业微信截图_15688847396118](https://user-images.githubusercontent.com/1614519/65233623-b6d14c00-db05-11e9-96a3-4fd825e6beca.png)

I think there is something wrong with the pixels.

**Comment by liberty752** [comment]
this is the whole image.

![exampleLib](https://user-images.githubusercontent.com/1614519/65233756-f304ac80-db05-11e9-8393-b3bfcb9c84ec.jpg)

**Comment by NPCompress** [comment]
@liberty752 

I was unable to reproduce the issue using the GUI v3.1.4064

![image](https://user-images.githubusercontent.com/18406717/65276059-fcd1e400-daf4-11e9-812d-9f13edef5fa7.png)

Can you provide more details as to how this was produced either using v3.1.4064 CLI or through an application you developed using the SDK libs or master GitHub sources?

**Comment by liberty752** [comment]
@NPCompress 
Thanks very much for your kind reply. 
Yesterday I used 
`git clone --recursive https://github.com/GPUOpen-Tools/Compressonator.git`
to update all the codes. Then compiled them to get a Compressonator_MDd.lib library. I put this library in my project companied with the include files.
However, my purpose is to change the jpg/png/tga into DX1/DX3/DX5. So I cannot use the example which is using a dds format file as the source data. I add the stb_image.h to get the data from the image, then make the srcTexture of CMP_Texture type by myself. Exactly I am not sure that the srcTexture format(CMP_FORMAT_BGR_888) is right. I show my main.cpp. Also I give the Compressonator_MDd.lib.

#include <stdio.h>
#include <string>

#include "Compressonator.h"
#include "DDS_Helpers.h"
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

bool g_bAbortCompression = false;
bool CompressionCallback(float fProgress, CMP_DWORD_PTR pUser1, CMP_DWORD_PTR pUser2)
{
    UNREFERENCED_PARAMETER(pUser1);
    UNREFERENCED_PARAMETER(pUser2);

    std::printf("\rCompression progress = %2.0f", fProgress);

    return g_bAbortCompression;
}

bool LoadImageFile(const char* pszFile, CMP_Texture& texture)
{
    int w, h, n;
    unsigned char *data = stbi_load(pszFile, &w, &h, &n, STBI_rgb);

    memset(&texture, 0, sizeof(texture));
    texture.dwSize = sizeof(texture);
    texture.dwWidth = w;
    texture.dwHeight = h;
    texture.dwPitch = 0;

    if (n == 4)
        texture.format = CMP_FORMAT_BGRA_8888;
    else
        texture.format = CMP_FORMAT_BGR_888;

    texture.dwDataSize = CMP_CalculateBufferSize(&texture);
    texture.pData = (CMP_BYTE*)malloc(texture.dwDataSize);
    memcpy(texture.pData, data, texture.dwDataSize);
    stbi_image_free(data);

    return true;
}

int main(int argc, const char* argv[])
{
    const char*     pszSourceFile = "exampleLib.jpg";
    const char*     pszDestFile = "exampleLib.dds";
    CMP_FORMAT      destFormat = CMP_FORMAT_DXT1;
    float           fQuality = 0.05f;

    CMP_Texture srcTexture;
    if (!LoadDDSFile(pszSourceFile, srcTexture))
    {
        LoadImageFile(pszSourceFile, srcTexture);
    }

    //===================================
    // Initialize Compressed Destination 
    //===================================
    CMP_Texture destTexture;
    destTexture.dwSize = sizeof(destTexture);
    destTexture.dwWidth = srcTexture.dwWidth;
    destTexture.dwHeight = srcTexture.dwHeight;
    destTexture.dwPitch = 0;
    destTexture.format = destFormat;
    destTexture.dwDataSize = CMP_CalculateBufferSize(&destTexture);
    destTexture.pData = (CMP_BYTE*)malloc(destTexture.dwDataSize);

    //==========================
    // Set Compression Options
    //==========================
    CMP_CompressOptions options = { 0 };
    options.dwSize = sizeof(options);
    options.fquality = fQuality;
    options.dwnumThreads = 8;

    //==========================
    // Compress Texture
    //==========================
    CMP_ERROR   cmp_status;
    cmp_status = CMP_ConvertTexture(&srcTexture, &destTexture, &options, &CompressionCallback, NULL, NULL);
    if (cmp_status != CMP_OK)
    {
        free(srcTexture.pData);
        free(destTexture.pData);
        std::printf("Compression returned an error %d\n", cmp_status);
        return cmp_status;
    }

    //==========================
    // Save Compressed Testure
    //==========================
    if (cmp_status == CMP_OK)
        SaveDDSFile(pszDestFile, destTexture);

    free(srcTexture.pData);
    free(destTexture.pData);

    system("pause");
    return 0;
}

[Compressonator_MDd.zip](https://github.com/GPUOpen-Tools/Compressonator/files/3633907/Compressonator_MDd.zip)

**Comment by liberty752** [comment]
@NPCompress 
I think maybe there is something wrong when I use stb_image to get the data from the jpg/png files. So could you please help me to handle jpg/png files when I want to change them into DXT1/DXT3 format.

**Comment by liberty752** [comment]
I tried the CLI and SDK of release version 3.1.4064. The CLI can get right result. However, the SDK will get the wrong color like this. I used the Compressonator_MDd.lib which was downloaded from https://github.com/GPUOpen-Tools/Compressonator/releases
![1](https://user-images.githubusercontent.com/1614519/65494721-e4dcd480-dee7-11e9-8c13-2b9b87c21b0f.png)

**Comment by NPCompress** [comment]
@liberty752 
This is a known issue, v3.1 SDK swizzles RGB channels to BGR for DXT1 
The master branch has code removed this and uses RGB for DXT1

"** NOTE: The master SDK source has a DXTC swizzle fix, make sure any applications using the source (v3.1 and older) are adjusted accordingly, BC6H and BC7 are not affected by this change, for details ref: Closed Issue #59**"

I will set up an example code that uses stb_image to load and compress jpg/png images to DXT1/DXT3 using the updated master source and save it to a DDS file format

**Comment by liberty752** [comment]
@NPCompress 
Thanks a lot for your help. I can use the "system" function to run the CLI in my project and that can meet my need.
