### ISSUE TITLE
[Request] OSX Support

### ISSUE THREAD

**Issue by MattOstgard** [GPUOpen-Tools/Compressonator#8]
My team makes WebGL games, we all use OS X, and our artists need to export to ATC on a regular basis. I haven't been able to find an ATC converter for OS X. It would be fantastic if Compressonator added Mac/Unix build support at least for the command line tool. Is that a possibility?

**Comment by xooiamd** [comment]
hi, thanks for your interest in compressonator. As for now, the plan to support Mac/Unix for the application tools (both commandline and gui) won't happen quickly, keep a watch on this site if there is any update on this. A possible solution for now is you can build the SDK libs and include the header file "Compressonator.h" then call the function CMP_ConvertTexture(&srcTexture, &destTexture, &options, &CompressionCallback, NULL, NULL) from your app.  You can refer to https://github.com/GPUOpen-Tools/Compressonator/blob/master/Compressonator/Examples/Compressonator_Test.cpp on example of a simple commadline app with the SDK. Hope this helps. thanks.

**Comment by quiret** [comment]
Compressonator is filled with Win32 native function calls. Somebody should port it to clean C++.

**Comment by NPCompress** [comment]
#ifdef _WIN32 compiler directive will be added to the code to identify Win32 native functions, to assist in port to cross-platform C++

**Comment by jhurliman** [comment]
Is this implemented?

**Comment by NPCompress** [comment]
This feature is not implemented.

There is no near term plan to port to other operating systems. Identifying win32 components under a compile directive will make the code unusable until alternate code is available.

**Comment by mems** [comment]
Actually I'm on macOS 10.12 and Compressonator works fine with wine
I just need `winetricks vcrun2015` and override `api-ms-win-crt-time-l1-1-0` to native (winecfg)

See [Is there a command line ATI texture compression tool? - Game Development Stack Exchange](http://gamedev.stackexchange.com/questions/9870/is-there-a-command-line-ati-texture-compression-tool#comment229111_30715)

But it's would be better to have at least a native CLI for UNIX platforms to use it in our workflow
