### ISSUE TITLE
Signed image compression

### ISSUE THREAD

**Issue by tbotting** [GPUOpen-Tools/compressonator#94]
Hello,

I'm trying to convert a normal map image in the R8G8B8A8_UNORM format to a normal map image with the format BC5_SNORM. This gives artifacts.

BC5_SNORM:
https://gyazo.com/10d5300db1b053e2eb16d486b4e0139c

BC5_UNORM:
https://gyazo.com/21dcbfa8cc12759d645555ea5b11555c

Am I missing any configs or is this feature not supported yet?

Thank you for your work on this library :)

**Comment by NPCompress** [comment]
@tbotting  Thank you for your support.

You are correct, SNORM formats are currently not supported.

**Comment by tbotting** [comment]
Are there any plans to support this in the future? I think it would be useful (and better for performance?) to be able to sample normal maps as SNORM, instead of having to do the following:

`map * 2.0 - 1.0`

**Comment by NPCompress** [comment]
@tbotting Yes, support for SNORM will be added.

**Comment by NPCompress** [comment]
@tbotting  Can you supply the original images you used to test with above, compressed and uncompressed as a zip file?

**Comment by NPCompress** [comment]
@tbotting SNorm support is added to v4.1 release
