### ISSUE TITLE
CMP_GetMipLevel doesn't seem to work

### ISSUE THREAD

**Issue by theakman2** [GPUOpen-Tools/compressonator#96]
The `CMP_GetMipLevel` function doesn't seem to work here:

https://github.com/GPUOpen-Tools/compressonator/blob/master/Compressonator/CMP_Framework/Compute_Base.cpp#L698

```
void CMP_API CMP_GetMipLevel(CMP_MipLevel *data, const CMP_MipSet* pMipSet, int nMipLevel, int nFaceOrSlice) {
    CMP_CMIPS CMips;
    data = CMips.GetMipLevel(pMipSet, nMipLevel, nFaceOrSlice);
}
```
The `data` parameter is not actually modified. Perhaps the function should be updated to return a `CMP_MipLevel *` like this:

```
CMP_MipLevel *CMP_API CMP_GetMipLevel(const CMP_MipSet* pMipSet, int nMipLevel, int nFaceOrSlice) {
    CMP_CMIPS CMips;
    return CMips.GetMipLevel(pMipSet, nMipLevel, nFaceOrSlice);
}
```

Alternatively it could take a `CMP_MipLevel **` parameter, but that seems ugly.

**Comment by NPCompress** [comment]
@theakman2 Thanks for the suggestions to fix, since we are already using ** on various other API, we will be consistent and use CMP_MipLevel **

**Comment by NPCompress** [comment]
@theakman2 v4.1 api is updated to use:
void CMP_API CMP_GetMipLevel(CMP_MipLevel** data, const CMP_MipSet* pMipSet, int nMipLevel, int nFaceOrSlice)
